### ISSUE TITLE
Toolbar blockInsert Issue overflow

### ISSUE THREAD

**Issue by rkboyz124** [outline/rich-markdown-editor#104]
### Bug or Enhancement
Bug

### What's The Issue/Purpose
"Block Insert Button" shows on the bottom of the page (below the editor) when the editor is set to minimum height.

### Expected Output
"Block Insert Button" should not show up below the editor, only inside the vertical boundaries of the editor or its parent component.

### Reproducible Demo
Check [repo here](https://codesandbox.io/s/rich-text-editor-toolbar-blockinsert-reproduction-fixed-9wb7u) to reproduce.

or see image here:

![test](https://user-images.githubusercontent.com/12042986/60653785-4e1af180-9e7d-11e9-8174-4713762c8260.jpg)

### Other Notes
It's a bit of a "hit or miss" bug since users would sometimes scroll up using the scrollbar (removing the focus on the newline).

**Comment by tommoor** [comment]
Thanks for filing. As of v10 the editor has been re-written, so this issue is no longer applicable.
