### ISSUE TITLE
Extra white space inserted at end of converted inline mark after closing with spacebar

### ISSUE THREAD

**Issue by Aerlinger** [outline/rich-markdown-editor#109]
Try typing some simple inline text in the editor that includes a mark such as `**test**` and press space. After doing so an extra empty space will be inserted after the text node and before the closing `**` mark (i.e. it will serialize to `**test **` instead of `**test**`.

**Resulting editor object model:**
```js
{
  "object": "value",
  "document": {
    "object": "document",
    "data": {},
    "nodes": [
      {
        "object": "block",
        "type": "paragraph",
        "data": {},
        "nodes": [
          {
            "object": "text",
            "text": "test ",
            "marks": [
              {
                "object": "mark",
                "type": "bold",
                "data": {}
              }
            ]
          }
        ]
      }
    ]
  }
}
```

Note the empty blank space after the end of "test" in the first node.

This also shows up in the rendered markdown like so:

`**bold **`

but should instead be:

`**bold** `

**Proposed fix**:

Rather than adding a bold/italic/code/etc mark to the node during the spacebar keypress event (`onSpace`) it should probably be closed during the keypress for the closing character. In other words `**bold**` would have the "bold" mark immediately added as soon as I press the last `*`. This would also fix issues where the text doesn't get converted to a bold node if I press enter instead of space, or have any character other than a space after the mark. For instance `**test**.` won't be converted to a bold node.

Happy to submit a PR if it's worth doing so.

**Comment by Aerlinger** [comment]
I have this working locally and can submit a PR if interested.

**Comment by tommoor** [comment]
Go for it. The main reason I hadn't took this on yet is because I felt the need to refactor that code pretty heavily 🙈

**Comment by Aerlinger** [comment]
Done. See https://github.com/outline/rich-markdown-editor/pull/112
