### ISSUE TITLE
Images with left-align, right-align options and text wrap

### ISSUE THREAD

**Issue by satyadeepk** [outline/rich-markdown-editor#11]
Support for left, right, center align options for images will be pretty useful!
It will allow us to wrap text along side the images.

Something like Dropbox Paper does:
![image](https://user-images.githubusercontent.com/478578/41763474-ffa2e6c8-761b-11e8-9362-7f4e1d486c40.png)

**Comment by tommoor** [comment]
This was completed a while back

**Comment by matbrgz** [comment]
Why? Sorry but I did understand why it will be awhile back?

**Comment by tommoor** [comment]
The feature has been implemented: https://github.com/outline/rich-markdown-editor/pull/345
