### ISSUE TITLE
update link address onBlur

### ISSUE THREAD

**Issue by julesair** [outline/rich-markdown-editor#114]
At the moment, the link address is only updated when pressing "Enter" after typing into the link toolbar. When closing the link toolbar by clicking somewhere outside, the change is lost. 

Would it be possible to also update the link "onBlur" of the link toolbar? I think, that would be the expected behavior.

[Update]: There is actually a "handleOutsideMouseClick" function in the code, that should do exactly that. It seems like it is not working properly in my case?

**Comment by tommoor** [comment]
Thanks for the report 😄
