### ISSUE TITLE
Unable to add code block to a numbered list

### ISSUE THREAD

**Issue by a-gvo** [outline/rich-markdown-editor#118]
Pasting the markdown for the following:
1. testing 123

 ```
 $ echo hello
 $ echo goodbye
 ```
2. testing 234

Results in this in the editor:
![markdown_bug](https://user-images.githubusercontent.com/7433568/66411290-8290d300-e9c1-11e9-81d3-9f3c83b9c382.png)

Directly typing the three ticks in between the numbered items also doesn't work. The cursor just jumps up to the top item and never generates the code box.

**Comment by tommoor** [comment]
Hey, this is an expected limitation – block-level elements such as quotes, code, images can only live at the top of the document.

If you'd like to add code in a list you can do so with inline code (single backticks in Markdown). Hope this makes sense.

**Comment by a-gvo** [comment]
Hey, makes sense. Thanks for the very quick response!
