### ISSUE TITLE
Editor crashes in Firefox and Safari if there is a `defaultValue` with a code block in CodeSandbox

### ISSUE THREAD

**Issue by ricokahler** [outline/rich-markdown-editor#119]
Open this code sandbox in Firefox or Safari (tested on a mac):

https://codesandbox.io/s/crazy-goodall-cf86l?fontsize=14

I get this error:

<img width="428" alt="image" src="https://user-images.githubusercontent.com/10551026/68077177-8c75de00-fd95-11e9-8762-fbd9b86a34cf.png">

This occurs if there is a `defaultValue` that contains a code block like so

    ```js
    const test = 'test';
    ```

It works fine on Chrome though.

**Comment by tommoor** [comment]
Hi @ricokahler – have you tried it outside of CodeSandbox? I do see the reproduction there – but running the exact same defaultValue locally on the latest version works fine…

![image](https://user-images.githubusercontent.com/380914/68093691-23ea3800-fe4d-11e9-8579-e2e8037df186.png)

**Comment by ricokahler** [comment]
I have not tried it outside of CodeSandbox. I just tried creating a "production build" of the sandbox (using the production build feature) and it seems to be working fine there? 🤷‍♀️

http://csb-cf86l.netlify.com/

Well if you don't foresee this as an issue then I'm good to close this. I found that downgrading to version 6.1.1 works in code sandbox.

Thanks for the support!

**Comment by tommoor** [comment]
The repo contains an example directory that you can run with `yarn start`, I'd recommend trying it out there rather than CodeSandbox. This is definitely weird, but without the ability to reproduce outside the sandbox I don't think I'll be able to prioritize a fix :(

**Comment by ricokahler** [comment]
That's fair and I don't expect a fix for this weird issue. Feel free to close. Thanks again!
