### ISSUE TITLE
Ability to programmatically change editor value

### ISSUE THREAD

**Issue by dboris** [outline/rich-markdown-editor#120]
Is it possible to use the editor as a controlled component, or is there a way to programmatically change `editorValue`?

**Comment by tommoor** [comment]
The only way currently would be to add a `key` value and force a re-mount, obviously this will lose the users cursor etc though. 

I would be happy to accept a PR that enables this ability.

**Comment by TommyJackson85** [comment]
@tommoor @dboris I will  work on this.

**Comment by TommyJackson85** [comment]
@tommoor something like this in what you mean by a key value? https://stackoverflow.com/questions/35792275/how-to-force-remounting-on-react-components

Would you be interested in a PR that enables an ability it allow programmatical edits aswell as human input edits at the same time?

**Comment by tommoor** [comment]
Hey, yes – that's what I mean – a `key` prop. Would be open to a PR that allows programatic edits through the value prop 👍

**Comment by TommyJackson85** [comment]
@tommoor please take a look at the pull request I made in relation to this issue.

I am looking for feedback from anybody as I might be going off track with the required task.

**Comment by TommyJackson85** [comment]
I just need clarity on somethings. Would you of expected the key prop to be used in the src/index or the example/index?
