### ISSUE TITLE
How to customize serializer

### ISSUE THREAD

**Issue by jacargentina** [outline/rich-markdown-editor#128]
I need to customize the built-in serializer; how can i do that? Cheers!

**Comment by tommoor** [comment]
The easiest way would just be to fork the repository and replace out the serializer with your own. `slate-md-serializer` has extensive tests which should make it easier to edit.

**Comment by jacargentina** [comment]
@tommoor would you accept a PR on adding, for example, a `serializer` prop to `Editor` ? When not defined, it would default to `slate-md-serializer`

**Comment by tommoor** [comment]
Is your usecase to add HTML support? Whilst it'd be a simple prop to add I don't really see a valid usecase for a custom serializer that still uses the same rendering code… it'd be great to understand your intention.

**Comment by jacargentina** [comment]
i’m trying to add a custom mark/block, via plugin

So i need to save/load those too, i have any other option ?

**Comment by tommoor** [comment]
No other option, you're right – could your custom mark be useful in the project itself or is it _very_ custom?

**Comment by jacargentina** [comment]
I'm thinking it is _very_ custom; a custom serializer is the only option for my use case. 

Another way would be to ditch completely `rich-markdown-editor` and use directly the `slate` editor, but that what i dont get all the `rich-markdown-editor` features already there....

**Comment by TommyJackson85** [comment]
I'm happy to procede with this task tommoor.

**Comment by jacargentina** [comment]
@TommyJackson85 can look at my PR?
