### ISSUE TITLE
Inconsistencies between the new line toolbar and edit existing line tool bar.

### ISSUE THREAD

**Issue by TommyJackson85** [outline/rich-markdown-editor#139]
I find that there seem to be inconsistencies between the two toolbars.

For example, I can choose to create a list bullet point on the new line tool bar (the toolbar that pops up after pressing the plus icon.):

<img width="680" alt="Screenshot 2019-12-08 at 18 42 43" src="https://user-images.githubusercontent.com/22279028/70394205-902aff00-19ea-11ea-8159-3661aabb0ba4.png">

But I can’t on the edit existing line toolbar (the one that pops up after clicking a line.):

<img width="398" alt="Screenshot 2019-12-08 at 18 43 35" src="https://user-images.githubusercontent.com/22279028/70394210-b0f35480-19ea-11ea-82bb-c688913bcb7f.png">

Visa versa, I can create a link on the edit existing line toolbar, but can’t on the other. I found it hard to find the 'add a link' button when first using the app. Maybe from first launching the new line tool bar, a link button would exist. When clicking it, it would first prompt the user to create a link title first, and then a new link, or both at the same time showing two inputs stacked on top of each other. 

Some buttons don’t need to exist on the edit existing line toolbar, like the hr line button or image button, but after creating each, options to remove them should be easily available on click.

Another issue I noticed is, when clicking an empty line (as apposed to the plus icon), it prompts the edit line tool bar, in which some buttons can't work. Maybe it should prompt the new line toolbar when it is empty.

If you have any critical feedback on what I am suggesting, like any pros and cons to it, it would be good to hear. This is only from my own user testing. :)

If this post is too broad and contains too many individual issues, I can edit it down and post each issue as new issue posts.

**Comment by tommoor** [comment]
Thanks for filing. As of v10 the editor has been re-written, I believe the difference between the block toolbar and the floating toolbar is more clearly discerned now.
