### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by justinmoon** [outline/rich-markdown-editor#144]
Instances of `localStorage` in [this file](https://github.com/outline/rich-markdown-editor/blob/2bf3d7a2c111175d3d95b94bc3957535d7c44b6d/src/plugins/CollapsableHeadings.js#L27) break server-side rendering

**Comment by rcmenezes** [comment]
Any idea how to bypass this error until it's fixed?

**Comment by tommoor** [comment]
Published a fix as `v9.11.2`
