### ISSUE TITLE
Is there a plan to implement slate >0.50 sometime in the next 4 months?

### ISSUE THREAD

**Issue by alexisvincent** [outline/rich-markdown-editor#145]
Hi there, thanks for this editor! It's saved us tons of time!

I know maintainers hate getting these kinds of questions but, is there a plan to implement slate >0.50 sometime in the next 4 months?

I'm trying to decide if I bite the bullet and fork with an upgrade (in cljs, so unfortunately not usable by this project) or if I can hold out while this work is done here. If there is a plan to implement slate 0.50 here it would be helpful to have a loose ETA (obviously with no guarantees!) so I can pace my other work.

Thanks again for the lib!

**Comment by tommoor** [comment]
Hi, no problem. There is no current plan to upgrade to 0.50 right now – I'm currently investigating moving this project to Prosemirror as a more sustainable long-term solution.

**Comment by alexisvincent** [comment]
Interesting! What's the motivation of the switch?

**Comment by tommoor** [comment]
- Slate continues to make major breaking changes on a regular basis. Eg 0.50 is a complete re-write of plugins again. We're trying to build a business ontop of the editor and it's unworkable to be rewriting everything every 3 months.
- Better soft keyboard/mobile support. 0.50 improved this a lot, but Prosemirror is still ahead.
- Realtime collaboration, prosemirror has first class support and detailed working implementations for client/server.

**Comment by tommoor** [comment]
I'm closing this to combine with https://github.com/outline/rich-markdown-editor/issues/143
