### ISSUE TITLE
The toolbar :before and :after styling extends past the container of the editor

### ISSUE THREAD

**Issue by jryd** [outline/rich-markdown-editor#149]
I've been trialing this out in an application and love the capabilities that it comes with. 

That said, the toolbar is causing some issues with the UI for the page, specifically the :before and :after pseudo selectors on the toolbar have a background colour meaning that it is overlapping content that exists outside the content container:

![image](https://user-images.githubusercontent.com/13251203/72852362-0ca74200-3cfa-11ea-8975-c7d9794a8765.png)

Is there a way to prevent this happening that I've missed?

**Comment by tommoor** [comment]
There's nothing built into the editor currently to prevent this, it expects to be full-bleed. The design is likely to change soon to be a little less obnoxious but in the meantime the best bet is to just wrap the whole editor in an `overflow: hidden` wrapper

**Comment by jryd** [comment]
🤦‍♂ of course you can just do that with CSS - completely overlooked this.

Works perfectly if you hide the overflow 😄.
