### ISSUE TITLE
Toolbar dividers still present when no blocks enabled

### ISSUE THREAD

**Issue by jryd** [outline/rich-markdown-editor#151]
We're looking to implement a markdown editor with a really limited number of fields. Really, all we want are controls for bold, italic, and linked text, and then ordered and unordered lists.

To this affect, our `hiddenToolbarButtons` configuration looks a little like this:

```js
const hiddenToolbarButtons = {
  blocks: [
    'image',
    'table',
    'heading1',
    'heading2',
    'heading3',
    'block-quote',
    'todo-list',
    'code',
    'horizontal-rule',
  ],
  marks: ['deleted', 'code']
};
```

This hides all the controls that we don't want, but leaves the dividers for them in place:

![image](https://user-images.githubusercontent.com/13251203/72867710-902d5700-3d2b-11ea-81a5-bf5beab9e5e0.png)
![image](https://user-images.githubusercontent.com/13251203/72867724-9b808280-3d2b-11ea-880b-8e3bf5305659.png)

Is there anyway to update this through the theme? I couldn't see any ability to do this.

**Comment by tommoor** [comment]
Thanks for filing.

The editor has been completely re-written from scratch, the option `hiddenToolbarButtons` has been removed so this issue is no longer applicable.
