### ISSUE TITLE
Markdown shortcuts wrapped by backticks should not trigger markdown

### ISSUE THREAD

**Issue by no-stack-dub-sack** [outline/rich-markdown-editor#153]
First off, thanks for your work on this editor! For the most part, its been a pleasure to work with. The only issues I've found for my current use-case are around markdown, [some of which have already been reported](#110). For instance:
```
The addition, or `+`, operator...
```
It is difficult to write lots of markdown with punctuation. I regularly have to add an extra space, then add my punctuation, then backspace to bring the punctuation up against the formatted code. But, I can work around this.

One issue that I haven't found reported yet (and apologies if I've missed it), which I can't seem to work around, is that markdown shortcuts should not be considered markdown shortcuts if they are wrapped by backticks. For example, from what I can tell, it seems impossible to correctly render the following:

```
The basic arithmetic operators are: (`-`, `+`, `*`, `/`). The `*` operator is...
```

This should render:

> The basic arithmetic operators are: (`-`, `+`, `*`, `/`). The `*` operator is...

But instead, it renders:

> The basic arithmetic operators are: (-, +, _, /). The  operator is..._

Demo:
![image](http://g.recordit.co/UgRjOGzswX.gif)

Other editors, like Slack, do not apply markdown styles when the trigger chars are wrapped in backticks. Or if they do, undo will revert the application of any markdown styles to offer the user greater control. Perhaps either or both of these solutions could be considered?

Another example is `++`. It seems that if I try to use this twice, anywhere in the editor, everything in between the two uses gets highlighted, even when `++` is wrapped with backticks. `**` is also problematic. Some way to escape characters or avoid this behavior would be super helpful. 

Thanks again!

**Comment by tommoor** [comment]
Hi Peter, the editor is currently being completely rebuilt on this branch:
https://github.com/outline/rich-markdown-editor/pull/150

I'd take a look and see if the behavior better matches your expectations

**Comment by no-stack-dub-sack** [comment]
@tommoor Thanks, yeah, I was looking at that PR and the pinned issue, and meant to say that maybe the rebuild will cover this. I figure enhancements aren't being made to the current build at this point, unless they're critical bugs...

Let me know! Any timeline on when you expect #150 to be ready to go?

**Comment by no-stack-dub-sack** [comment]
Also, I did find a workaround to the first issue, but it involves excluding the `*` on the first pass, and then adding it in at the very end when everything else is done. As long as you don't press the spacebar afterwards, you can get it right :smile:
