### ISSUE TITLE
Warning: Failed prop type: Invalid prop `leaves` supplied to `Leaf`

### ISSUE THREAD

**Issue by hariria** [outline/rich-markdown-editor#155]
Hi I recently received this error and wanted to know how i could fix this?
```
index.js:1 Warning: Failed prop type: Invalid prop `leaves` supplied to `Leaf`, expected a Slate `List<Leaf>` but received: List [ Leaf { marks: Set {}, text: "asdf laksdjfl ;aksdjf l;aksjdf asd;lfk jasdlfkj a;lsdkfj a;ls" } ]
```

**Comment by tommoor** [comment]
Hey, I couldn't tell you I'm afraid – it looks like a warning, not an error and is likely part of the underlying [Slate](https://github.com/ianstormtaylor/slate) library that currently powers the editor

**Comment by hariria** [comment]
Not Experiencing any errors since this package's update to 10.0.0!
