### ISSUE TITLE
Placeholder Props not updating Component placeholder

### ISSUE THREAD

**Issue by hariria** [outline/rich-markdown-editor#157]
I pass in a placeholder but it's not overriding placeholder text. No matter what I put for the placeholder it says:

```
## Write Something...
...Or dont
```

**Comment by tommoor** [comment]
Hey Andrew, the version you’re referring to on NPM is a pre-release and is
not ready for production yet

**Comment by hariria** [comment]
which npm version of this package should i install for the slate version of the editor?

**Comment by tommoor** [comment]
You should pin to `^9.0.0`
