### ISSUE TITLE
"Block Insert Button" is a submit button

### ISSUE THREAD

**Issue by dave-db** [outline/rich-markdown-editor#159]
v10.0.0-4

The `block-menu-trigger` button has no `type="button"` set, meaning it acts as a submit button if the editor is being used inside a form, which then submits the whole thing. A bit unexpected!

**Comment by tommoor** [comment]
Thanks for the spot. Please note that the 10x series is a prerelease and not stable.

**Comment by dave-db** [comment]
Absolutely, understood - just experimenting atm. Although `npm install rich-markdown-editor` does install the 10 beta by default - should `latest` dist-tag still be on 9? Apologies if I'm covering old ground.

**Comment by dave-db** [comment]
Same issue with `heading-anchor` in `readOnly` mode, for the record.

**Comment by tommoor** [comment]
I don't know why `npm` does that tbh, it's clearly a semantic prerelease.

**Comment by dave-db** [comment]
Agreed!

Thanks for your work on the library, it's ace.

**Comment by tommoor** [comment]
I overwrote the tag to point specifically to 9.x

**Comment by mikecx** [comment]
Is anyone seeing this issue again? Using the latest 11.3.1 and clicking the '+' causes my form to submit.

**Comment by tommoor** [comment]
Looks like it regressed a couple of weeks ago
