### ISSUE TITLE
Sorry, an error occurred uploading the image

### ISSUE THREAD

**Issue by BackOrder** [outline/rich-markdown-editor#162]
Hiya! I'm getting the following error when uploading images on Outline using either Safari or Google Chrome.

<img width="609" alt="Capture d’écran, le 2020-04-11 à 20 01 11" src="https://user-images.githubusercontent.com/8844578/79057406-44ee5a80-7c2f-11ea-8cbe-d537eda7e195.png">

**Comment by tommoor** [comment]
On `getoutline.com`? Could you check in developer tools under the "Network" and "Console" tabs for errors.

**Comment by BackOrder** [comment]
I would say it's installed on our server, it's on `outline.<our-domain-name>`. There are few oddities such as trying to upload images or changing my avatar. Perhaps misconfigured? I am not the admin but I can pass information along, if you have instructions for us.

**Comment by tommoor** [comment]
Yes, this is definitely a misconfigured self host. I recommend contacting the admin, there is nothing we can do here. They can reach out to hello@getoutline.com to purchase a support contract if they'd like help setting it up.
