### ISSUE TITLE
Block menu background

### ISSUE THREAD

**Issue by arjunnaha** [outline/rich-markdown-editor#163]
I'm using the Prosemirror fork, as it actually appears a lot more stable than 9.x!

I set the background property on the theme to be transparent, to blend in with the page. I think [this line here](https://github.com/outline/rich-markdown-editor/blob/prosemirror/src/components/BlockMenu.tsx#L336) should read:
```javascript
background-color: ${props => props.theme.blockToolbarBackground};
```

Otherwise, you wouldn't be able to set separate background colours for the editor vs the block menu. More than happy to submit a PR if needed.

![image](https://user-images.githubusercontent.com/7504589/80217653-f5992880-8637-11ea-94fc-480eb3ca1603.png)

**Comment by tommoor** [comment]
Thanks, addressed
