### ISSUE TITLE
Browser scrolls to the bottom of the page, when the editor is enabled

### ISSUE THREAD

**Issue by viktordueck** [outline/rich-markdown-editor#164]
Hi. 

In my new project I'm using the current master (based on the Prosemirror fork) of the editor. Usually the editor is read-only and the user can enable it to change the content. The problem is, every time the editor is activated (readonly -> editable) the browser scrolls to the bottom of the page (not the editor). That does not happen, when the editor is set back to readonly.

Example:
![example](https://user-images.githubusercontent.com/63724078/80234995-56852880-8659-11ea-8b14-a32a99161188.gif)

The shown example is generated with a simple test-app. You can find it here: https://github.com/viktordueck/test-rich-markdown-editor.

The steps to create this example were:
- create-react-app
- add packages for lodash and rich-markdown-editor
- replace the sample code in App.js

The relevant code in App.js is 

    const [readOnly, setReadOnly] = useState(true);
    const enableEditor = () => {
      setReadOnly(false);
    };

    return (
      {readOnly ? (
        <button onClick={() => enableEditor()}>Edit</button>
      ) : (
      <>
        <button onClick={saveAndCloseEditor}>Save</button>{' '}
        <button onClick={cancelEditor}>Cancel</button>
      </>
      )}

      <Editor
        key={'editor_' + editorId}
        defaultValue={savedText || ''}
        onSave={saveEditor}
        onCancel={cancelEditor}
        onChange={handleChange}
        onClickLink={(href) => console.log('Clicked link: ', href)}
        onClickHashtag={(tag) => console.log('Clicked hashtag: ', tag)}
        onShowToast={(message) => window.alert(message)}
        readOnly={readOnly}
        autoFocus={true}
      />
    )

I was able to trace it back to RichMarkdownEditor.componentDidUpdate(prevProps). The problem occurs when the editor view of prosemirror is updated:

    if (prevProps.readOnly !== this.props.readOnly) {
      this.view.update(Object.assign(Object.assign({}, this.view.props), { editable: () => !this.props.readOnly }));
    }

But I'm lost there. I am not sure whether this is an issue with my implementation, the rich-markdown-editor or the prosemirror-view. I hope you can help.

Thank You very much.

**Comment by tommoor** [comment]
Remove `autoFocus` ?

**Comment by viktordueck** [comment]
Removing `autofocus`does not help. I also have the same issue with latest chrome, latest firefox and latest safari on mac and ios.

I did some more debugging and found out, that the scrolling is done by following function:

    function BlockMenuItem({ selected, disabled, onClick, title, shortcut, icon, }) {
      const Icon = icon;
      const ref = React.useCallback(node => {
          if (selected && node) {

            console.log("scroll:");
            console.log(node);
            debugger;

            smooth_scroll_into_view_if_needed_1.default(node, {
                scrollMode: "if-needed",
                block: "center",
            });
        }
      }, [selected]);
      return (React.createElement(MenuItem, { selected: selected, onClick: disabled ? undefined : onClick, ref: ref },
          React.createElement(Icon, { color: selected ? theme_1.default.black : undefined }),
          "\u00A0\u00A0",
          title,
          React.createElement(Shortcut, null, shortcut)));
    }

The `console.log` and `debugger` are mine. Output to the console is then:

    <button class="sc-AxmLO cPtcfm">
      <svg fill="#000" width="24px" height="24px" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="..."></path></svg>
        &nbsp;&nbsp;
        Big heading
      <span class="sc-fzozJi czUWwz">⌘ ⇧ 1</span>
    </button>

I think the reason is that `BlockMenu` has the the default setting `selectedIndex: 0`.

**Comment by tommoor** [comment]
That's useful, thanks… will take a look

**Comment by tommoor** [comment]
Addressed
