### ISSUE TITLE
Provide callback on image deletion

### ISSUE THREAD

**Issue by shankardevy** [outline/rich-markdown-editor#167]
Currently, I do not see an option to remove deleted images on the server. If a dedicated callback is provided for image deletion, then it can be helpful to trigger cleanup actions on the server.
 
Froala editor has one such:
https://froala.com/wysiwyg-editor/docs/events/#imageManager.beforeDeleteImage

**Comment by tommoor** [comment]
I don't think this is particularly useful as you could delete the image and then immediately CMD+Z to restore it. You should instead compare the content of the document when it's saved and detect any removed images at that point in time.

**Comment by shankardevy** [comment]
I agree with the undo functionality this is not required. Do you have any recommendations on how to manage (delete) images on the server? I could think of a regex search for images on a the document before and after saving, compare the results and do a manual cleanup. 

Not sure if this is the best way. Any sample implementation could help.

Feel free to close this issue.

**Comment by tommoor** [comment]
Yes, either a regex for finding markdown images which should be fairly small or use a library like https://github.com/remarkjs/remark/tree/master/packages/remark-parse to parse the markdown into an AST and then iterate through that to find the images.
