### ISSUE TITLE
headingsOffset has no effect

### ISSUE THREAD

**Issue by arjunnaha** [outline/rich-markdown-editor#168]
(Prosemirror and updated to 10.0.0-10)

The `headingsOffset` doesn't seem to have any effect on headings in the editor. The [Heading.js component](https://github.com/outline/rich-markdown-editor/blob/master/src/components/Heading.js#L29) seems to take the prop into account though.

**To reproduce:**
1. Set `headingsOffset` prop to 2
2. `/h1 + enter` for a size 1 heading

**Actual behaviour**
![image](https://user-images.githubusercontent.com/7504589/81224277-5ed94e00-8fdf-11ea-9d7d-31ebe0ea409d.png)

**Expected behaviour**
Heading should be `h3`.

**Comment by tommoor** [comment]
Fixed in `v10.0.0-11`
