### ISSUE TITLE
Collapsible headings

### ISSUE THREAD

**Issue by tommoor** [outline/rich-markdown-editor#169]
v9 offered the ability to collapse content beneath headings, v10 removed this in the first version – it would be nice to restore it.

The way this should likely work is to have "collapsing" a heading add a Prosemirror decoration to everything between the heading and the next one of the same level or above. The decoration can add a class which hides the content.

**Comment by benhowes** [comment]
:+1:  Would be especially useful if it supported pasting `<summary><details>` commonly found in github markdown!
