### ISSUE TITLE
Add highlight to formatting toolbar

### ISSUE THREAD

**Issue by tommoor** [outline/rich-markdown-editor#172]
Highlight was always supported, but only through the keyboard shortcut. It might be nice to have an icon in the formatting toolbar specifically for this.

**Comment by maxvoltar** [comment]
WIP: https://share.goabstract.com/e66d3cb2-cac0-437e-aac2-be3f5fec461a

**Comment by maxvoltar** [comment]
Icon: https://share.goabstract.com/9fd0e8bd-a678-43a0-ac4a-d2c63ca97d2d

![image](https://user-images.githubusercontent.com/125779/81326219-cbb11e80-9099-11ea-9fd0-a7df66b2f7d9.png)

**Comment by tommoor** [comment]
![image](https://user-images.githubusercontent.com/380914/81461465-e39fa580-9160-11ea-8d51-e90c465d65b9.png)

Implemented.
