### ISSUE TITLE
Placeholder functionality

### ISSUE THREAD

**Issue by monicakogler** [outline/rich-markdown-editor#173]
In v9 I could include the `placeholder` prop to set placeholder text for the editor.

In the latest v10 release, that no longer has the beta disclaimer, replaces this with 

> Type '/' to insert…

From the code and docs, it looks like this is not intended but maybe the docs are outdated.

Recommendations on getting the placeholder back? Is v10 still beta-ish?

Thanks! <3

**Comment by tommoor** [comment]
Yep, it's still prerelease – as indicated by the version number. Thanks for filing, will address.

**Comment by monicakogler** [comment]
thanks!
