### ISSUE TITLE
Add emoji insert menu

### ISSUE THREAD

**Issue by tommoor** [outline/rich-markdown-editor#175]
Typing `:` followed by a shortcode should allow searching and inserting emojis, eg:

`:heart` – it can trigger a menu in the same style as the block insert menu and filter as you continue to type.

### Github
![image](https://user-images.githubusercontent.com/380914/81426524-2ab07b00-910e-11ea-9bac-eef204a3a4dc.png)

### JIRA
![image](https://user-images.githubusercontent.com/380914/81426467-179dab00-910e-11ea-9446-2504a41cfe36.png)

### Dropbox Paper
![image](https://user-images.githubusercontent.com/380914/81426582-3f8d0e80-910e-11ea-8512-3cec5dfe7324.png)

**Comment by TommyJackson85** [comment]
@tommoor there's alot of open source emoji pickers, including [your own](https://github.com/tommoor/emojione-picker)
Maybe we could use one of the open source versions for this?

**Comment by tommoor** [comment]
It's true – I have a similar module, I'd say it's a solid maybe – I think I'd like to keep the menus in a consistent list style and the integration with Prosemirror itself complicates things a little but no doubt there is a lot of crossover.

**Comment by TommyJackson85** [comment]
Let me give this a shot. I will create a PR on it. I will start by creating a popup from typing ':'.

**Comment by TommyJackson85** [comment]
@tommoor would it be a good idea to use the BoxMenu, BoxMenuItem code to pass in listings of emojis? Only thing is its prompted from the start of a new line only and I am looking to bypass that. Could create an Emojis menu set in the menus folder maybe.

Or should I just create it from scratch?

**Comment by JiangWeixian** [comment]
@tommoor hi, i implement simple version for emoji, but it looks like need `markdown-it-emoji` to parse it. Any plan to support add custom markdown-it plugin to rules 🤣

![emoji](https://github.com/JiangWeixian/with-emoji/blob/master/snapshots/with-emoji.gif?raw=true)

**Comment by tommoor** [comment]
Looks like a great start – why not contribute a PR?

**Comment by AnishDe12020** [comment]
This would be an awesome feature to have, so is it happening?
