### ISSUE TITLE
Unable to "check" todolist items

### ISSUE THREAD

**Issue by ScottLindley** [outline/rich-markdown-editor#176]
Version: `10.0.0-13`

**Expected behavior**
I can check off todo list items or write one manually using some format like `-[x]`.

**Observed behavior**
I can't seem to ever place a todo listed item into a "checked" state.

Here's a how I'm rendering the component.
```
<Editor
  id={props.entry.id}
  readOnly={!!props.readOnly}
  defaultValue={body}
  headingsOffset={1}
  onChange={(handleChange: () => string) => {
    setBody(handleChange());
  }}
  onSave={(val: string) => console.log({ val })}
/>
```

![gif](https://user-images.githubusercontent.com/21317789/81460730-371bee80-9175-11ea-8453-09ae0ba812c4.gif)

**Comment by tommoor** [comment]
Are you passing the value from onChange back into `defaultValue`?

**Comment by ScottLindley** [comment]
I was passing the value back to `defaultValue`. However, I don't believe that's the issue.

I ran the example locally and verified it works in Chrome but does **not** on Firefox version 76.0 (64-bit). So now I'm thinking this is a browser compatibility issue. Does this fall out of the domain of this library? Should I instead open an issue in the Slate repository?

**Comment by tommoor** [comment]
It’s within scope 👍

**Comment by tommoor** [comment]
Safari is even worse, the checklist's are basically unusable – looks like that component might need a rethink, as of yet I'm not sure exactly why it's being so finicky.

**Comment by ScottLindley** [comment]
🎉
