### ISSUE TITLE
Method to customise markdown serialisation

### ISSUE THREAD

**Issue by dave-db** [outline/rich-markdown-editor#183]
I'm currently integrating the editor into an existing site which already has a body of content, written mostly in things like VSCode with `prettier` enabled. The existing markdown has a few conventions, such as using dashes for unordered lists and underscores for emphasis (list not exhaustive). Any time I open an existing document to edit in `rich-text-editor`, as well as any changes I make, the editor replaces those characters with asterisks.

What options are available for customising the editor's markdown serialisation preferences? I've looked through the source but can't see a way to override or supply a configuration to the underlying serialiser.

**Comment by tommoor** [comment]
> What options are available for customising the editor's markdown serialisation preferences?

There is no configuration for this and I don't plan on incorporating any I'm afraid. The editor outputs compliant Markdown and a proliferation of options would result in a more bug-prone implementation that's difficult to maintain.

Based on your usecase and #184 I'd recommend just forking the editor and customizing for your usecase.

**Comment by dave-db** [comment]
Understood, makes total sense. Thanks for your consideration anyway. Presumably overriding the serialiser used in the constructor would take care of this?

**Comment by tommoor** [comment]
It would, the parser should already handle the different list formats
