### ISSUE TITLE
Build without So.js

### ISSUE THREAD

**Issue by jorilallo** [outline/rich-markdown-editor#19]
`slug` imports `So.js` which is huge. Thoughts on moving to webpack compiling to ignore this on the package level?

For library users: add `new webpack.IgnorePlugin(/unicode\/category\/So/)` to reduce build size.

**Comment by tommoor** [comment]
> Thoughts on moving to webpack compiling to ignore this on the package level?

Not 100% sure I follow but down for reducing package size by any means

**Comment by jorilallo** [comment]
@tommoor moving the ignore from library user (host application) to library build step. Now that I think about it, not sure if that would even work

**Comment by iamtekeste** [comment]
@jorilallo I also want to reduce the size of this package, where do I add 
`new webpack.IgnorePlugin(/unicode\/category\/So/)`? Is it on my own webpack config or on this library's?

And is So.js not needed?

**Comment by tommoor** [comment]
Hi, this issue is very old – the library no longer depends on `slug`.

**Comment by iamtekeste** [comment]
I understand this is a full fledged editor and the size is reasonable but can you suggest anyway to reduce the file size? According to bundlephobia it is at 223KB minified+gzipped.

https://bundlephobia.com/result?p=rich-markdown-editor@10.0.0

**Comment by tommoor** [comment]
There's a way to reduce the size of lodash down to only the parts used as part of webpack bundling, I'd take a look at that. Would happily accept a PR.

**Comment by iamtekeste** [comment]
Thank you for the quick response. I will take a look into that. Awesome editor by the way!
