### ISSUE TITLE
Checkbox list with trailing empty checkbox will cause to not render whole list.

### ISSUE THREAD

**Issue by josephbuchma** [outline/rich-markdown-editor#191]
Checkbox list with trailing checkbox without any text will cause to not render whole list.

[DEMO](https://codesandbox.io/s/inspiring-meninsky-vupjv?file=/src/App.js)

**Version**
10.0.0

**Comment by tommoor** [comment]
The markdown you're rendering was not produced by the editor, correct?

**Comment by josephbuchma** [comment]
I updated [demo](https://codesandbox.io/s/inspiring-meninsky-vupjv?file=/src/App.js) with markdown produced by editor.
If you remove trailing `[ ]` it renders properly.

**Comment by josephbuchma** [comment]
:facepalm: sorry, it's my bad. Output markdown was trimmed by accident before saving.
