### ISSUE TITLE
Add ability to have new lines in tables

### ISSUE THREAD

**Issue by tommoor** [outline/rich-markdown-editor#206]
Currently new lines are converted to spaces (stripped). Newlines can probably be encoded with `<br>`, this matches other products, although there is no accepted standard for this.

**Comment by giofcosta** [comment]
Hi @tommoor , which tables do you refer? The tables of the Editor?

**Comment by tommoor** [comment]
Yes, the tables that you insert with `/table` command. Newlines are collapsed as part of writing to markdown.

I believe this is quite a tricky issue because of the integration between Prosemirror <-> Markdown-it, for example this is the method that renders a markdown table:

https://github.com/outline/rich-markdown-editor/blob/develop/src/lib/markdown/serializer.js#L303

I'd imagine for deserialization of the newlines we'd need an additional plugin similar to: 
https://github.com/outline/rich-markdown-editor/blob/develop/src/lib/markdown/breaks.ts

**Comment by giofcosta** [comment]
I've read the docs and maybe the problem is the on-enter-key-press event. I think you can't override it, but maybe you can solve this problem using an alternative event like on-ctrl+enter-key-press.

**Comment by ktfth** [comment]
So, the change need to be on the project of rich-markdown-editor with a version for our case?

**Comment by tommoor** [comment]
Yes, all issues tracked in this repo can be fixed entirely in this
codebase.

**Comment by alexjosesilva** [comment]
abilitys:

1. desenvolvimento de software com Php, Java, SQL, Javascript
2. Git, Github
3. Mysql, Postgresql
3. Heroku, AWS
