### ISSUE TITLE
Drag and reorder block work in proseMirror but not in here

### ISSUE THREAD

**Issue by castroCrea** [outline/rich-markdown-editor#215]
In the exemple https://prosemirror.net/
When we select a content and we drag n drop it it work but weirdly not with rich markdown editor.

Do you know why ?

**Comment by tommoor** [comment]
I haven’t looked into it, there is a ‘draggable’ part of the nodespec but
I’m not sure if more is needed to fully enable it.

**Comment by castroCrea** [comment]
If you talk about https://prosemirror.net/docs/ref/#model.NodeSpec.draggable
It's not that this is not working, I think maybe the original drag has been overwriting maybe by the image node ?

**Comment by castroCrea** [comment]
@tommoor I just check by disabled the Image node on the build and you can drag n drop content, so I can try to found where it come from. If you have any idea that can make win some time?!
