### ISSUE TITLE
type error: a.node.getBoundingClientRect is not a function

### ISSUE THREAD

**Issue by MatheusRV** [outline/rich-markdown-editor#236]
Seems related to editor.

**To Reproduce**
1. Copy a Google Docs
2. Paste in a New or Existing Document
3. Boom! Error happen!

**Expected behavior**
Paste document in Outline

**Version**
0.43.3

**Screenshots**
![image](https://user-images.githubusercontent.com/23284276/87354144-73344c80-c534-11ea-8683-0e54d1764e1a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Latest

**Comment by tommoor** [comment]
This should be fixed here https://github.com/outline/rich-markdown-editor/issues/232 – which means it'll be in the next version of Outline. I was never able to reliably reproduce though, so I'll give these steps with pasting from GDocs a try.

**Comment by MatheusRV** [comment]
Tks @tommoor !!!
