### ISSUE TITLE
Realtime editing

### ISSUE THREAD

**Issue by ShiroYacha** [outline/rich-markdown-editor#24]
Hi, 

I would like to know if it's possible to impl. realtime editing by feeding the slate value to the underlying slate editor when a document is modified in the database. It seems that now the only "defaultValue" is exposed...

Thanks!

**Comment by tommoor** [comment]
The editor isn't designed for this usecase yet, you'd probably need to be able to show other users cursors too at a minimum. As it stands it would be relatively easy to allow though and a welcome improvement 😄

**Comment by ShiroYacha** [comment]
Now I'm doing it using the ref which is a pretty ugly hack... Something like:
```
    render() {

        if (this.editorRef.current && checkRemoteContent()) {
            const value = MarkdownSerializer.deserialize(this.state.remoteContent);
            this.editorRef.current.setState({ editorValue: value });
        }
        return (<Editor
            ...
            ref={this.editorRef}
            ... />);
    }
```
In this way, at least the updates will be in real-time, however, I haven't find a way to effectively merge the content of each user so you won't lose the cursor when an update arrives...

Ideally, if the editor exposes the value prop of the editor it would be pretty easy to inject the incoming content. To be more inline with the current structure, we can probably wrap a `valueOverride` prop that gets deserialized and overrides the editorValue state inside `componentWillReceiveProps`?

**Comment by tommoor** [comment]
@ShiroYacha If you put in a pr that exposes `value` and updates the editorValue internally when the prop changes I'd be happy to accept.

**Comment by jfrolich** [comment]
Wouldn't it be easier to do realtime editing on the underlying markdown value as it's just plain text? To me that seems way easier to implement server and client-side than mutations on the complex json document especially when merging different states.

**Comment by jfrolich** [comment]
BTW if you are interested to contribute this back (or fork), I am really interested in this as well.

**Comment by ShiroYacha** [comment]
Hey, actually originally I just wanted a way to feed the editor value back from remote. I am not really doing real collaboration editing...The slate editor already has an issue open on this subject and has supported to some level OT check https://github.com/ianstormtaylor/slate/issues/259.

**Comment by tommoor** [comment]
> Wouldn't it be easier to do realtime editing on the underlying markdown value as it's just plain text

I think that would likely come undone once you got into the details - doing OT on the Slate structure would allow keeping selection and cursor positions for example. Considering there is a wider effort in the Slate ecosystem to enable realtime it would be good to participate in that…

**Comment by tommoor** [comment]
I'm closing this issue – the editor has been rebuilt to be based on Prosemirror, which makes adding realtime editing much easier through their plugins architecture. However the work to do so will not be included as part of this project.
