### ISSUE TITLE
Adding styles to previous lines. 

### ISSUE THREAD

**Issue by VarunRustomji** [outline/rich-markdown-editor#243]
- When I select a style attribute for a new line, the style gets added to the previous line instead of the selected line.

**To Reproduce**
1. Write something on a line
2. Go to the next line and select H1

**Expected behavior**
The style should be added to the current line and not the previous line.

**Version**
    "next": "latest",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "rich-markdown-editor": "^10.4.0"

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: chrome
 - Version 10.15.6

The error can be seen in the repo [here](https://github.com/VarunRustomji/editor-test)

My editor file has the following code:  

```
import RichMarkdownEditor from "rich-markdown-editor";
import { useState } from "react";

const Editor = () => {
  const [readOnly, setReadOnly] = useState(false);
  // const [savedText, setSavedText] = useState("");

  const handleChange = (value: any) => {
    console.log(value());
  };

  return (
    <div style={{ paddingLeft: 32, paddingTop: 12 }}>
      <button onClick={() => setReadOnly(!readOnly)}>{readOnly ? "Read Only" : "Editable"}</button>
      <br />
      <br />
      <RichMarkdownEditor id="example" readOnly={readOnly} onChange={handleChange} />
    </div>
  );
};

export default Editor;

```

**Comment by tommoor** [comment]
Thanks for repro steps – this is already filed as #233
