### ISSUE TITLE
Select all and delete leads to `RangeError: Position -1 out of range`

### ISSUE THREAD

**Issue by pixelkritzel** [outline/rich-markdown-editor#248]
Deleting all text in an editor by selecting `CMD+A` and deleting it with backspace `←` causes the `RangeError: Position -1 out of range` to be thrown

**To Reproduce**
1. Go to https://codesandbox.io/s/adoring-chandrasekhar-td3wk?file=/src/App.js
2. Focus on the editor
3. Select All via `CMD+A``
4. Delete all via backspace `←`
5. Error

**Expected behavior**
Just emptying the editor

**Version**
10.5.0-1

**Desktop (please complete the following information):**
Firefox, Chrome, Safari
Current versions at 08. August 2020

**Comment by SMBurrows** [comment]
+1
