### ISSUE TITLE
Questions about mobile

### ISSUE THREAD

**Issue by ShiroYacha** [outline/rich-markdown-editor#25]
Hi,

It seems like the editor doesn't work very well in mobile: markdown is not recognized, some issues with keyboard interaction... I would like to know the current status of support for mobile and the milestones for it.

It's a really awesome editor in general and if you provide some pointers I could find time to work on it as well :)

Thanks!

**Comment by aulneau** [comment]
I think the issues with mobile don't stem from this project, from from Slate, the editor that this project is using. There are open issues regarding mobile support in editor that seem like they will be looked at soon :)
