### ISSUE TITLE
BlockToolbar light theme default icon color

### ISSUE THREAD

**Issue by ShiroYacha** [outline/rich-markdown-editor#26]
Hi, 
I saw that the light theme uses
`
  blockToolbarBackground: colors.greyLight,
  blockToolbarTrigger: colors.greyMid,
  blockToolbarTriggerIcon: colors.white,
`
This make the block toolbar not really visible. I think we should probably use something other than `colors.white` for the trigger icon?

![image](https://user-images.githubusercontent.com/4082699/43963520-cbb73f56-9cba-11e8-8733-f015774cb29b.png)

I can create a PR if needed. 

PS: I have a general question regarding the relation between this repo and the [outline repo](https://github.com/outline/outline). Are they always in sync? And for all issues regarding the editor, it should be put here?

Best

**Comment by tommoor** [comment]
@ShiroYacha this looks like a mistake.

The two repos aren't always in sync although I'm trying to keep them close.

**Comment by ShiroYacha** [comment]
Ah I see, the problem is that the context toolbar and the insert toolbar shares the same foreground color. I have changed the context background because I thought it's more inline with the light theme.

**Comment by ShiroYacha** [comment]
Ok I have changed the PR to meet this requirement.

**Comment by tommoor** [comment]
Thanks!

closed by 2b6f1a915ee9789a9853a5dcfac2830f1bd56126
