### ISSUE TITLE
Strange behavior when creating a new element

### ISSUE THREAD

**Issue by aablinov** [outline/rich-markdown-editor#261]
I'm trying to create a new project from scratch and use rich-markdown-editor, I think I miss some important detail, but not find it. I tried much more combination: use package.json from repo, use package.json from outline, and many others but unsuccessfully.

**To Reproduce**
1. Create plain project
2. Type something
3. Type "/" and select Bullet list for example
4. Caret goes upstairs to the previous element

**Expected behavior**
Create a bullet list. If you clone https://github.com/outline/rich-markdown-editor and build from the sources this is not reproduced. This is not reproduced in https://github.com/outline/outline too

**Version**
10.6.6-0

**Screenshots**
![ezgif-7-a262bee7d092](https://user-images.githubusercontent.com/24268143/91945836-bb3b4880-ed07-11ea-8a18-d1b46a530171.gif)

**Desktop (please complete the following information):**
 - OS: Mac 0.15.6 
 - Browser chrome
 - Version Version 84.0.4147.125

package.json
```
{
  "name": "testeditor",
  "private": true,
  "scripts": {
    "start": "webpack-serve --config ./webpack.config.js"
  },
  "dependencies": {
    "@babel/preset-react": "^7.10.4",
    "exports-loader": "^0.6.4",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "rich-markdown-editor": "^10.6.6-0",
    "webpack-serve": "^3.2.0",
    "babel-loader": "^8.1.0"
  }
}
```

source.js

```
import * as React from "react";
import ReactDOM from 'react-dom'
import RichMarkdownEditor from "rich-markdown-editor";

const element = document.getElementById("main");

class Example extends React.Component {
  render() {
    return (
      <div>
        <RichMarkdownEditor />
      </div>
    );
  }
}

if (element) {
  ReactDOM.render(<Example />, element);
}

```

index.html

```
<!doctype html>
<html>

<head>
  <meta charset="UTF-8">
  <title>Example</title>
  <style>
    body {
      margin: 0;
      padding: 0;
    }

    #main {
      padding-top: 100px;
      width: 80vw;
      max-width: 1040px;
      min-height: 100vh;
      margin: 0 auto;
    }
  </style>
</head>

<body>
  <div id="main"></div>
  <script src="dist.js"></script>
</body>

</html>
```

webpack.config.js

```
const path = require("path");

module.exports = {
  mode: "development",

  resolve: {
    mainFields: ["browser", "main"],
    extensions: [".ts", ".tsx", ".js"],
  },

  entry: path.resolve(__dirname, "src", "source.js"),

  output: {
    filename: "dist.js",
    path: path.resolve(__dirname),
  },

  module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: [
          path.join(__dirname, 'node_modules')
        ],
        include: [
          path.resolve(__dirname, "src"),
        ],
        options: {
          cacheDirectory: true,
          presets:['@babel/react']
        }
      }
    ]
  },
};
```

**Comment by tommoor** [comment]
A similar issue occurred recently when the wrong version of `prosemirror-transform` was installed – did you use `npm` to install which would ignore the `yarn.lock` perhaps? Double check which version of that package is in place

**Comment by iamtekeste** [comment]
I am also facing this issue. Here is a [CodeSandBox](https://codesandbox.io/s/react-forked-l41u3?file=/index.js) that reproduces this issue. Add an H1 and then hit enter and select H2 from the menu, instead of letting you write the text for the H2 element it turns the previous H1 element into an H2.

**Comment by aablinov** [comment]
Hello, thank you for your help I catch it.

In my case, I delete prosemirror-transform 1.2.8 from yarn.lock and everything is ok.

<img width="936" alt="Screenshot 2020-09-03 at 8 37 24 PM" src="https://user-images.githubusercontent.com/24268143/92148646-8ae9cc00-ee25-11ea-92ab-36ddcc4f1671.png">

```
prosemirror-transform@1.2.5, prosemirror-transform@^1.0.0, prosemirror-transform@^1.1.0, prosemirror-transform@^1.2.1:
  version "1.2.5"
  resolved "https://registry.yarnpkg.com/prosemirror-transform/-/prosemirror-transform-1.2.5.tgz#7a3e2c61fcdbaf1d0844a2a3bc34fc3524e9809c"
  integrity sha512-eqeIaxWtUfOnpA1ERrXCuSIMzqIJtL9Qrs5uJMCjY5RMSaH5o4pc390SAjn/IDPeIlw6auh0hCCXs3wRvGnQug==
  dependencies:
    prosemirror-model "^1.0.0"
```

**Comment by tommoor** [comment]
`npx yarn-deduplicate yarn.lock` can help with removing duplicate packages from the lockfile.

**Comment by tommoor** [comment]
closing as it's a consequence of having this incompatible package installed, hopefully above should be enough for anyone still experiencing this ^^

**Comment by nicslaine** [comment]
New Line issue - https://www.dropbox.com/s/ee71ftklqw0rdxm/doublespace.mkv?dl=0

**Comment by aablinov** [comment]
@nicslaine please check my answer https://github.com/outline/rich-markdown-editor/issues/261#issuecomment-686646576
