### ISSUE TITLE
Switching from non-empty value to empty value 

### ISSUE THREAD

**Issue by arthurysong** [outline/rich-markdown-editor#262]
I'm trying to use rich-markdown-editor as an editor for journaling. I want the value of the Editor component to switch from a full journal entry to an empty one. When the value of the editor goes from non-empty to an empty value, the editor doesn't display the empty value.

Is this an intended feature??

**Example of Use**
```
import React, { useState } from 'react'
import Editor from 'rich-markdown-editor';

const Test = () => {
    const [value, setValue] = useState("Blah blah blah");

    return <div>
        <Editor defaultValue={"meow"} value={value} />
        <button onClick={() => setValue("")}>Button 1</button>
        <button onClick={() => setValue("Rawr")}>Button 2</button>
    </div>
}

export default Test
```
**Expected Behavior**
When I press Button 1, the editor should be empty, and the placeHolder should be displayed.

**Screenshots**
![outline](https://user-images.githubusercontent.com/48899712/92062643-11cb7580-ed4e-11ea-9301-7b453844cf9a.gif)

**Version**
10.6.5

**Comment by tommoor** [comment]
Seems like a bug~ish – I'd recommend adding a `key` prop to the editor that changes when you change journal entry, usually the database id.

**Comment by arthurysong** [comment]
Oh okay, yeah it works when I provide a unique id for the key. Thanks a lot!
