### ISSUE TITLE
Make styled-components a peer dependency

### ISSUE THREAD

**Issue by joshuaslate** [outline/rich-markdown-editor#268]
When using `rich-markdown-editor` in my app (which also uses v5.1.x of `styled-components`), I noticed the following console warnings:

```
ServerStyleSheet.js:66 It looks like there are several instances of 'styled-components' initialized in this application. This may cause dynamic styles not rendering properly, errors happening during rehydration process, missing theme prop, and makes your application bigger without a good reason.

See https://s-c.sh/2BAXzed for more info.
```

From what I've gathered from the link in the warning, I believe `styled-components` should be a `peerDependency` and `devDependency` and should be passed to the `externals` object in the webpack config. More info: https://webpack.js.org/guides/author-libraries/

I'm happy to make a PR for this myself, I just wanted to see if there was a reason it wasn't done this way before making the changes.

**To Reproduce**
1. In an application with `styled-components` as a dependency, add a `rich-markdown-editor` on a page where you're using other `styled-components`.
2. Refer to console.

**Expected behavior**
Styled-components would be a peer dependency and no warning would appear, as it would not be bundled with `rich-markdown-editor`.

**Version**
10.6.7

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: 85.0.4183.83 (64-bit)

**Comment by tommoor** [comment]
That solution sounds fine to me, it'll have to be a major version number change when published
