### ISSUE TITLE
External plugin order

### ISSUE THREAD

**Issue by ShiroYacha** [outline/rich-markdown-editor#28]
Hi again 😀,

I have a question regarding the additional slate plugins setup. It seems that currently additional plugins will be added after outline's plugins:
`this.plugins = this.plugins.concat(props.plugins);` 

I wonder shouldn't the external plugins have a higher priority in the building sequence? Because external plugins can always default to the outline plugins by not processing in certain conditions but the not the other way around. 

Best!

**Comment by tommoor** [comment]
You know, I'm yet to find a situation where the order has actually made a difference – but that makes sense and fits in with the semantics of other hooks such as `renderNode`
