### ISSUE TITLE
Cursor moves to the start on every setState.

### ISSUE THREAD

**Issue by bchhabra2490** [outline/rich-markdown-editor#285]
I am using React 16.12 and onChange, I update the state using useState Hook. When the state updates, it rerenders and the cursor moves to the front. So, getting backward text. Used the exact same code available in the example.
**To Reproduce**
1. Use React 16.12
2. Use same code given in example.

**Expected behavior**
Should edit normally.

**Version**
Using `^11.0.0-4`

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [safari]

**Comment by tommoor** [comment]
The editor is not controlled, only change `value` when you want to reset it.

**Comment by JiangWeixian** [comment]
> The editor is not controlled, you should only change the `value` prop when you explicitly want to reset it. Which example are you referring to – mind linking so I can update it?

in `index.stories.tsx`, if pass value to editor in is way, cursor will auto jump to start of line

```tsx
const Template: Story<Props> = args => {
  const [value, setValue] = useState()
  return <Editor {...args} value={value} autoFocus={true} onChange={(v) => {
    setValue(v())
  }} />;
};
```

there is similar issue https://github.com/facebook/react/issues/2047#issuecomment-144194817.

I have no idea about how prosemirror to fix it
