### ISSUE TITLE
Has a hard time with larger amounts of data.

### ISSUE THREAD

**Issue by aulneau** [outline/rich-markdown-editor#29]
Hey everyone!

Really enjoying this project, I've learned a lot by playing around with this. 

I've noticed an issue where if I'm testing larger amounts of text data, let's say 100 paragraphs or so, the editor will hang pretty intensely. I'm not exactly sure why. I thought it was because of how I was saving data to my redux store, but after switching it so we'd pull the data from a local cache first, it still hung. I tested it on getoutline.com and when I put in a larger amount of data to a document, it actually just crashes the whole tab.

I haven't been able to dig in yet, but my first ideas are it might be related to something with how this wrapper is processing saved data/historical changes or something. I've tested on just a vanilla slate editor and it can take huge amounts of text data.

I'll report back as I have more time to dig in, but if this is a known limitation or issue, I'd love any direction :)

Thanks! and thanks for the great library.

**Comment by tommoor** [comment]
It could be that the editor is being pretty aggressive about serializing back to markdown on any change, that's where I'd start looking at least.

Always willing to accept patches for performance improvements 😄

**Comment by aulneau** [comment]
Hmm yeah after some more digging I think it's specifically the `Markdown.deserialize(props.defaultValue)` function that causes the hang on initial load. I wonder if we can make it more async. It'd be cool to pass the length of content/line count and render a placeholder or at least prevent the component from being blocking.

**Comment by tommoor** [comment]
Are you trying with plain paragraphs or more complex documents? I just tried creating hundreds of paras with no issue. I wonder if there is some particular object that is slower to parse than others

**Comment by tommoor** [comment]
_thinking_

I don't think it would be too much of a problem to have the serializer parse in "chunks" on larger files and actually a really good idea. It would mean a breaking change though so that that we can return a promise rather than the result from the deserialize method.

**Comment by jorilallo** [comment]
@tommoor I noticed that Paper for example only renders one page worth of stuff on load, and then renders the rest

**Comment by tommoor** [comment]
Yea, I think that would be ideal too but more of a Slate concern

**Comment by aulneau** [comment]
Awesome, yeah I was thinking it'd be great to chunk or segment the data that the editor was using. My first thought was that it'd be cool to load the first page immediately and then merge in prefetched data as the user went on. It seems like there aren't any performance drags once the editor has mounted and has the data. 

The way I have been testing is generating ~150 paragraphs on lipsum.com and pasting it in, and on paste and then reload is when the editor hangs most (sometimes 5+ seconds).

**Comment by aulneau** [comment]
I've tested 4.0 and the same issue exists where initial load hangs for ~4-5 seconds while it mounts with large data. I didn't really have any performance issues when it was mounted with data previously.

**Comment by hecor** [comment]
I have the same problem when I upgrade from 7.0 to 9.0.6
It will be extremely slow when loading larger amounts of text data.

Thanks for the great library and hope to get any help.

**Comment by hecor** [comment]
![image](https://user-images.githubusercontent.com/1171710/55237927-332d5580-526e-11e9-9e88-f05ef6180772.png)

Just found it will call normalize function two times when loading any document. I believe it called only  one time before v7.0

**Comment by tommoor** [comment]
I have an idea what's causing this, investigating…

**Comment by tommoor** [comment]
The double normalize is now fixed in production 🙌

**Comment by hecor** [comment]
> The double normalize is now fixed in production 🙌

Great, thanks for so quick response.
