### ISSUE TITLE
Adding todo or a list eats up a block

### ISSUE THREAD

**Issue by kuldeepk** [outline/rich-markdown-editor#290]
**To Reproduce**
1. I took the example from this repo
2. Add a line of text (let's call it `Line 1`) and press enter twice to leave a blank line
3. Add a line of text at the third line (let's call it `Line 3`)
4. Take the cursor to the second line (the one we left blank) and add the block type as either Bullet List, Ordered List, or Tasks List -> You will see that the blank line 2 gets deleted and `Line 3` gets converted into the Bullet List (or Ordered List, or Tasks List)

**Expected behavior**
It should not delete line 2. It shouldn't convert line 3 into a list block. It should only convert line 2 into a list block.

**Version**
`10.4.0`

**Screenshots**
![screencast](https://media4.giphy.com/media/XoIE354fp9QtgC4WGM/giphy.gif)

**Desktop:**
 - OS: Mac OS 10.14.6
 - Browser: Chrome 
 - Version 85.0.4183.102

**Comment by tommoor** [comment]
Thanks for the gif. Honestly the /slash menu is only supposed to be used on an empty line – so behavior outside of that is definitely "up for grabs", would be happy to see a fix for this though.

**Comment by kuldeepk** [comment]
Thanks for the response. The issue happens with the empty line as well. Here's how to reproduce. 

![empty line](https://media0.giphy.com/media/DyVU06QWzKl2UcBN0D/giphy.gif)

I tried to reproduce this on your editor on getoutline.com, but couldn't reproduce it there, but occurs on the editor from this repo. 

Thanks again for your help. FYI, we are using this editor at [Edition](https://edition.so)

**Comment by tommoor** [comment]
Ah, see this issue – https://github.com/outline/rich-markdown-editor/issues/261

It's likely you're hitting the same thing with the wrong version of `prosemirror-transform`

**Comment by kuldeepk** [comment]
ha! that makes sense. Thanks for pointing to the solution!

**Comment by tommoor** [comment]
Edition looks lovely btw, if you want to sponsor the repo at any point in the future I'm sure we could send traffic your way 😉
