### ISSUE TITLE
onSearchLink does not render with latest state

### ISSUE THREAD

**Issue by hoantran-it** [outline/rich-markdown-editor#291]
Hi team, I want to report a problem with rich-markdown-editor, please see below for more detail

**To Reproduce**
When searching using Link feature, the result list always shows the previous state instead of latest state.
In the video below, it should be the same as the text display.
https://recordit.co/4FkA50ZXec

**Expected behavior**
The result should be updated with the latest state.

**Version**
^11.0.0-4

**Device**
 - OS: MacOS
 - Browser:  Chrome
 - Version: 85.0.4183.83 (Official Build) (64-bit)

Thank you!

**Comment by tommoor** [comment]
I believe we were seeing a race condition in API responses, please try `v11.0.0-8` and see if it performs better.

If you're still seeing the issue I think it might be in your own code in the way that the API requests are handled – I'd suggest putting together a minimal reproduction.

**Comment by hoantran-it** [comment]
@tommoor The data I put to the display text and the rich-markdown-editor is the same, all of them are located in the same component, so I don't think it's a problem of API, the same data for both but rich-markdown-editor render differently. Anyway, let me try with v11.0.0-8, thank you!

<img width="795" alt="Screen Shot 2020-09-25 at 12 40 13" src="https://user-images.githubusercontent.com/13161875/94230502-489b4280-ff2c-11ea-981f-5b2eba413b51.png">
<img width="871" alt="Screen Shot 2020-09-25 at 12 42 26" src="https://user-images.githubusercontent.com/13161875/94230688-b47dab00-ff2c-11ea-862c-c6597ac523dd.png">

**Comment by hoantran-it** [comment]
@tommoor I tried with v11.0.0 but no luck, the problem here is I passed the same data to the display text and rich-markdown-editor but rich-markdown-editor always render the previous data. Could you please give me any advice? Thank you!

<img width="795" alt="Screen Shot 2020-09-25 at 12 40 13" src="https://user-images.githubusercontent.com/13161875/94232659-b6496d80-ff30-11ea-91f7-9655dae2ce14.png">
<img width="871" alt="Screen Shot 2020-09-25 at 12 42 26" src="https://user-images.githubusercontent.com/13161875/94232668-b9445e00-ff30-11ea-8980-d5903525fe73.png">

**Comment by tommoor** [comment]
`searchResult` seems to be coming from the context of the callback, it isn't mutated within the callback itself – so by definition it must be out of date. Your `async` function does not `await` the result of the search so this is why it's out of date.

It almost seems like you're treating it similar to a hook. I would expect your `setKeyword(term)` to be awaited and return the relevant results.

**Comment by hoantran-it** [comment]
Thanks @TommyJackson85 , let me try!
