### ISSUE TITLE
Problem typing multiple underscores in identifiers

### ISSUE THREAD

**Issue by pstuifzand** [outline/rich-markdown-editor#296]
When I type multiple underscores in identifiers, for example `hello_test_hello`, the middle test part becomes italic. This even happens when I start the identifier with backticks. It seems to me that it's not possible to type identifiers like that.

**To Reproduce**
1. Type: 
 ```
`hello_test_hello`
```
2. Output = hellotesthello, with "test" part italic.

**Expected behavior**
`hello_test_hello`

**Version**
Version in getoutline.com

**Screenshots**
![](http://mous.es/HTjw5y.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser Chrome
 - Version Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by tommoor** [comment]
Note: While the fix is merged it isn't deployed to production – but will be within 24h.
