### ISSUE TITLE
Uploading images with the same name does not work

### ISSUE THREAD

**Issue by aablinov** [outline/rich-markdown-editor#302]
Uploading images with the same name does not work

**To Reproduce**
1. Select "Image" in BlockMenu
2. Upload image (image.png for example)
3. Try to upload image with the same name(image.png)
**Expected behavior**
Upload two images

**Version**
All, I test on 10 and 11

Its happen because state of file input not changed
```
<input
 type="file"
 ref={this.inputRef}
 onChange={this.handleImagePicked}
 accept="image/*"
/>
```

I have solution for this bug, in BlockMenu.tsx need add before ```this.props.onClose();```
```
if (this.inputRef.current) {
  this.inputRef.current.value = "";
}
```

If this is a good solution let me know I will create PR.

**Comment by tommoor** [comment]
Ah yep, that sounds like a good solution 👍

**Comment by ScottAgirs** [comment]
Does anyone have usage example for image uploads?
