### ISSUE TITLE
Menu position varies between "/" vs plus button

### ISSUE THREAD

**Issue by k4mr4n** [outline/rich-markdown-editor#304]
**To Reproduce**

I'm using this library withing the chakra-ui project and it works fine. but, when I'm using the Editor inside a Modal the menu does not show with typing the "/" and only the plus button works.

Link to the video demonstrating this issue (in case gif is not understandable):

the video:
https://drive.google.com/file/d/1ZTiZgXn_nbZYxBxuTKxGQQp5zGsxQpvs/view?usp=sharing

**Screenshots**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/5468009/95392956-aa15c680-08c7-11eb-917c-d0831a9cd29e.gif)

**Version**
- "@chakra-ui/core": "^1.0.0-rc.3",
- "rich-markdown-editor": "^11.0.1"
- "styled-components": "^5.2.0"

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 85.0.4183.121

Can someone please help me on how can I fix this issue?
Thanks

**Comment by tommoor** [comment]
I don't know anything about chakra-ui, this one's probably down to you to figure out. Is the popover just hidden behind the modal?

**Comment by k4mr4n** [comment]
@tommoor it isn't the issue. css bottom property is calculated to be 728px which goes on the far bottom of the page that's the reason it doesn't show.
but when I click on the plus button css would be { top: 120px } and shows the menu correctly in place
This [video](https://drive.google.com/file/d/1ZTiZgXn_nbZYxBxuTKxGQQp5zGsxQpvs/view?usp=sharing) shows it clearly

**Comment by tommoor** [comment]
~700px looks about right based on your screenshot, try making the modal position relative?

**Comment by k4mr4n** [comment]
@tommoor I saw in another [thread](https://github.com/outline/rich-markdown-editor/issues/261#issuecomment-686646576) that `prosemirror-transform` version caused the issue so I fixed the version and its working like a charm now

**Comment by tommoor** [comment]
Oh interesting, didn't make that connection - glad you figured
