### ISSUE TITLE
Pasting code in a code-block doesn't work

### ISSUE THREAD

**Issue by y-gupta** [outline/rich-markdown-editor#306]
**To Reproduce**
1. Create a new code-block element
2. Copy plain text code from notepad
3. Try to paste the code inside the code-block element
4. Code block element disappears and the code loses whitespace formatting

**Expected behavior**
The whitespace is retained and code is actually pasted inside the element

**Version**
v0.48.1 of outline project from docker hub image

**Screenshots**
- The code-block element
  ![The code-block element](https://user-images.githubusercontent.com/2096049/95569436-8cc83000-0a60-11eb-947b-ad0d6afb73be.png)
- The plan text code being pasted
  ![The plan text code being pasted](https://user-images.githubusercontent.com/2096049/95569472-95b90180-0a60-11eb-85b0-d86046d31b23.png)
- After pasting the code inside the block
  ![after pasting the code inside the block](https://user-images.githubusercontent.com/2096049/95569490-9ce00f80-0a60-11eb-8a3b-661515a8a7c7.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 85

**Smartphone (please complete the following information):**
N/A

**Comment by tommoor** [comment]
Thanks, this was fixed here - https://github.com/outline/rich-markdown-editor/pull/295 - the fix will be in the next release.
