### ISSUE TITLE
Line feed characters inserted on newline

### ISSUE THREAD

**Issue by ukch** [outline/rich-markdown-editor#309]
**To Reproduce**
* Enter a line of text
* Press the return key a few times
* Enter another line of text
* Examine the generated markdown

**Expected behavior**
I would expect to see something like the following:
```markdown
A line of text

A second line of text
```
(That is, separated by newlines, a.k.a. carriage returns i.e. `\n`)

Instead I see this:

```markdown
A line of text&#xA;&#xA;\&#xA;A second line of text
```
(`&#xA;` is the HTML escape code for the line feed character i.e. `\r`)

When passing this generated markdown into the [simple-markdown](https://github.com/Khan/simple-markdown) renderer, I see something like the following:

> A line of text
> \\
> \      second line of text
> A

**Version**
10.6.4

**Comment by tommoor** [comment]
I'm not aware of anywhere in this library that inserts linefeed characters, so I'm not sure how those would have come about.

The backslashes are expected and how the editor encodes multiple new lines – something that Markdown itself does not support. You can strip them with `output.replace(/\n\\\n/g, "\n\n")`.

**Comment by ukch** [comment]
Thanks for the help @tommoor. On further inspection, it seems the linefeed characters were inserted by my browser (I was adding the output of this editor to DOM attributes, and it was happening then - I am now passing the output through `encodeURIComponent` and the issue no longer occurs)
