### ISSUE TITLE
Using "+" overrides previous block

### ISSUE THREAD

**Issue by jl-gogovapps** [outline/rich-markdown-editor#310]
It seems that when a user enters an initial block of content, then uses the "+", the initial block of content is overridden.

**To Reproduce**
1. Click "+" and choose H1
2. Type "Test" and hit the 'enter' key
3. Click "+" and choose a bulleted list
4. Observe that the cursor moves back and does not start a bulleted list

**Expected behavior**
I think the expected behavior here is a new content block is created that starts with a bullet list

**Version**
11.0.1

**Screenshots**
![14ts8GWT3j](https://user-images.githubusercontent.com/44532602/95905985-88a15880-0d67-11eb-8f1e-6dde860805d7.gif)

**Comment by tommoor** [comment]
You have the wrong version of `prosemirror-transform` installed, see this discussion for the solution:

https://github.com/outline/rich-markdown-editor/issues/261#issuecomment-686201757

**Comment by jl-gogovapps** [comment]
Thanks!
