### ISSUE TITLE
Table directly beneath table gets merged

### ISSUE THREAD

**Issue by tommoor** [outline/rich-markdown-editor#315]
**To Reproduce**
1. Create a table
2. Create another table directly undernearth
3. Reload from created Markdown
4. Tables are merged / broken

**Expected behavior**

Tables remain separate

**Comment by iamsaumya** [comment]
I can't reproduce this in my storybook. Is it fixed somehow?

**Comment by tommoor** [comment]
It's tricky to recreate in the storybook because you need the state to be persisted between reload – I don't think this is fixed yet

**Comment by tommoor** [comment]
I cannot reproduce this either anymore 🤷
