### ISSUE TITLE
Table of contents on live content

### ISSUE THREAD

**Issue by aulneau** [outline/rich-markdown-editor#32]
Hey again!

I'm curious if it's possible to show the Table of Contents always (ala dropbox paper), regardless of if the editor is in readOnly mode? see this line -> https://github.com/outline/rich-markdown-editor/blob/master/src/index.js#L271

Was this choice made for a specific reason?

Thanks!

**Comment by tommoor** [comment]
I guess we thought it would be less confusing perhaps? But I'm pretty open to changing it.
