### ISSUE TITLE
Removal of blank lines

### ISSUE THREAD

**Issue by shompoe** [outline/rich-markdown-editor#329]
On loading documents the editor seems to do some automatic clean up of the source text, which removes a lot blank lines. However, when a blank line separating a list from a table gets removed the table is no longer rendered.

* So this... 

| Column A | Column B |
|----|----|
| Abd | Def |

* Becomes this... 
| Column A | Column B |
|----|----|
| Abd | Def |

**Comment by tommoor** [comment]
Fixed in `v11.0.10`, thanks for reporting
