### ISSUE TITLE
Optimizing slate-drop-or-paste-images

### ISSUE THREAD

**Issue by jorilallo** [outline/rich-markdown-editor#33]
While auditing bundles I noticed that `slate-drop-or-paste-images` includes `mime-types` dependency which is pretty sizeable. As this lib uses a fixed list of allowed images it would be easy to replace the dependency with a hardcoded list of allowed mimetypes. E.g. change `extensions` prop into `validateImage` callback which would get either extension or the mimetype and  we would performs the validation on `rich-markdown-editor`. If this sounds good, happy to PR both libs.

**Comment by tommoor** [comment]
@jorilallo sounds reasonable, are you suggesting making those changes on my fork? I should move it to the outline org.

**Comment by jorilallo** [comment]
@tommoor yep was thinking that would probably be the easiest.

**Comment by tommoor** [comment]
Moved: https://github.com/outline/slate-drop-or-paste-images

**Comment by jorilallo** [comment]
@tommoor Looks like you probably forgot to push your latest changes to Github? The code there looks old (applyTransform vs insertImage)

**Comment by tommoor** [comment]
So yea, I royally screwed up here. I think the original source is lost – might have to recreate 😢

**Comment by jorilallo** [comment]
no worries, I could probably look it up from the compiled source

**Comment by tommoor** [comment]
It doesn't seem to depend on mime-types any more 

https://github.com/ianstormtaylor/slate-plugins/blob/master/packages/slate-drop-or-paste-images/package.json
