### ISSUE TITLE
Dark Mode dropdown & headers transparency/color invisible on dark background

### ISSUE THREAD

**Issue by DerekOsgood** [outline/rich-markdown-editor#336]
Dark mode headers and the dropdown are not legible on dark mode background colors.

<img width="579" alt="Screen Shot 2020-12-04 at 2 41 23 PM" src="https://user-images.githubusercontent.com/12837442/101222657-151d1880-363f-11eb-9c0b-46c686ef9759.png">
<img width="476" alt="Screen Shot 2020-12-04 at 2 41 43 PM" src="https://user-images.githubusercontent.com/12837442/101222661-164e4580-363f-11eb-8ae8-ddfea71d156a.png">

**Comment by tommoor** [comment]
Have you set a custom theme prop? See the included example file, this isn't what the editor looks like in dark mode by default

**Comment by DerekOsgood** [comment]
Ah, good catch - did have a custom background color set which I didn't realize.  However, even when removed, there's still issues with H1/H2/H3 visibility as font color is defaulted to black.  Table & Divider visibility is also a bit iffy due to dark-ish line color.  See attached.

![Screen Shot 2020-12-09 at 1 29 24 PM](https://user-images.githubusercontent.com/12837442/101699062-62c6c600-3a2f-11eb-8642-039b28a460e6.png)
![Screen Shot 2020-12-09 at 1 31 43 PM](https://user-images.githubusercontent.com/12837442/101699064-635f5c80-3a2f-11eb-8019-2cbf7c828f70.png)

**Comment by tommoor** [comment]
If it's defaulting to black it's because you haven't set the color. Passing a `theme` prop overrides the internal theme so you need to pass all colors, it's possible this behavior should be changed but that's how it works at the moment.

**Comment by tommoor** [comment]
Closing out as all of these colors can be chosen by passing the `theme` prop:

https://github.com/outline/rich-markdown-editor/blob/develop/src/theme.ts#L16
