### ISSUE TITLE
Unable to delete embedded tables/media

### ISSUE THREAD

**Issue by DerekOsgood** [outline/rich-markdown-editor#337]
Embedded formats & media like tables should be deletable using the delete key, just like text - currently once one is inserted, they're impossible to delete (or delete rows) or modify (e.g. adding rows).

**Comment by colinhacks** [comment]
I'm able to delete columns one-by-one by clicking on the menu handle at the top of each one, and once I've deleted all the columns, the table goes away. You can also add additional rows by pressing the ENTER key in any cell. 

Being able to delete them with backspace would be nice though. Or having the ability to delete rows as well as columns, like you mention.

**Comment by tommoor** [comment]
I'm confused, you can also delete rows or the entire table – are you guys not seeing this functionality?
 
![Kapture 2020-12-12 at 11 13 25](https://user-images.githubusercontent.com/380914/101992876-19fb5100-3c6b-11eb-970c-bbf1ac3e5114.gif)

**Comment by colinhacks** [comment]
Oops the handles on the left side of the table were hidden because I hadn't added any padding to the container div 🤦‍♂️

**Comment by DerekOsgood** [comment]
Yeah, now I'm seeing it - was hidden due to that dark mode theme issue from my other issue ticket.  Pair of false alarms, sorry :).  That said, still would be nice to be able to delete the entire table by using the delete key when on a line after it.  Not *super* intuitive to have to click a column header that only appears when the table is actually selected.  Or, just make the handles visible when nothing's selected too.
