### ISSUE TITLE
"Write a caption" doesn't work with Safari

### ISSUE THREAD

**Issue by arguiot** [outline/rich-markdown-editor#338]
The title is self-explanatory. When using this project on Safari, it is impossible for us to edit the caption under the image.

**Expected behavior**
It should work properly. I tried a fix which seems to work quite well:
- Add the following styles to the `<p>` element with the caption:
```css
-webkit-user-select: text;
user-select: text;
```

**Version**
11.0.8

**Desktop (please complete the following information):**
 - OS: macOS 11 Big Sur
 - Browser Safari
 - Version 14

**Comment by tommoor** [comment]
Thanks for filing, agree with your suggested fix 👍
