### ISSUE TITLE
Prosemirror Transform Issues on CRA

### ISSUE THREAD

**Issue by sonny3690** [outline/rich-markdown-editor#344]
Related to #261. 

When you only install the `rich-markdown-editor` package on a fresh CRA repository, you run through the following issue where selecting commands eats up one line below:

![](https://media.giphy.com/media/aYPnDnGNDGxpwGIPOq/giphy.gif)

**To Reproduce**
1. `npx create-react-app <name>` to create the CRA.
2.  Run `yarn add rich-markdown-editor` to install the dependency.
3.  Copy the `example/src/index.js` example to `index.js` with a few modifications (change 'main' to 'root', etc.) 

Someone also generated a sandbox with this issue [here](https://codesandbox.io/s/l41u3). Try creating a bulleted list above the text.

Also, a few solutions referred to cleaning up the `prosemirror-transform` versions in the lock file, but there's no `prosemirror-transform` in the `yarn.lock` file since we just installed it as a node_module. Not sure if others have had this issue of deleting lines using CRA?

### package.json
```
 "dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.1",
    "rich-markdown-editor": "^11.0.11",
    "styled-components": "^5.2.1",
    "web-vitals": "^0.2.4"
  },
```

**Expected behavior**
The command, such as a bullet, shouldn't eat up the line below.

**Version**
^11.0.11

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Comment by tommoor** [comment]
> a few solutions referred to cleaning up the prosemirror-transform versions in the lock file, but there's no prosemirror-transform in the yarn.lock file since we just installed it as a node_module

It would still be in the lockfile, it contains all dependencies and their sub-dependencies
