### ISSUE TITLE
Caret size at beginning of headers

### ISSUE THREAD

**Issue by tommoor** [outline/rich-markdown-editor#350]
After merging the floating images functionality (https://github.com/outline/rich-markdown-editor/pull/345) I noticed that when the cursor is placed at the beginning of a heading the caret is the wrong size, this is quite confusing and hints to the user that they won't be typing a heading.

It seems to be the difference between positioning the `::before` element relative or absolute, strangely.

cc @cliftonc

**Comment by cliftonc** [comment]
That is odd, I'll take a look and see if I can figure it out tomorrow.

**Comment by tommoor** [comment]
Definitely a css quirk of sorts!
