### ISSUE TITLE
Support multiple programming languages in the `code` block

### ISSUE THREAD

**Issue by jfrolich** [outline/rich-markdown-editor#38]
I have a pretty nice implementation in plain SlateJS. Will try to port that over to RME. Let me know if this is a welcome addition, or any ideas.

**Comment by tommoor** [comment]
It would be a welcome addition - the serializer _should_ support storing the language correctly, I'd imagine a select input in the top right of a code block in edit mode?

**Comment by jfrolich** [comment]
That's exactly what I have, I'll look into porting this
