### ISSUE TITLE
Failed to compile ./node_modules/outline-icons/lib/components/CheckboxIcon.js

### ISSUE THREAD

**Issue by FelipeGerolomo** [outline/rich-markdown-editor#386]
I use the following command line to install:

yarn add rich-markdown-editor

When i put the following code

import Editor from "rich-markdown-editor";

<Editor
  defaultValue="Hello world!"
/>

i got this error:

./node_modules/outline-icons/lib/components/CheckboxIcon.js

Module not found: Can't resolve 'core-js/modules/es.array.index-of.js' in 'C:\Projetos\LEXP\studentcare-web\node_modules\outline-icons\lib\components'

**Comment by dec0dOS** [comment]
The docs are not up to date. Use [RichMarkdownEditor](https://github.com/outline/rich-markdown-editor/blob/97d666f68de956f9b6fb14cc9e2601b99b6200b3/src/index.tsx#L1524)

**Comment by tommoor** [comment]
I'm not sure what you're referring to regarding the docs being out of date? @FelipeGerolomo could you try `v11.3.1` please
