### ISSUE TITLE
example page missing

### ISSUE THREAD

**Issue by thoughtlessmind** [outline/rich-markdown-editor#398]
The inbuilt example page is missing. The path of the page is https://github.com/outline/rich-markdown-editor/blob/HEAD/example/src/index.js  
This page link is mentioned in the document.

**To Reproduce**
1. Go to documentation and find the documentation of `onChange` prop. [Link](https://github.com/outline/rich-markdown-editor#onchange--value-void)
2. Click on `Inbuilt-example`
3. You'll be redirected to a new page that is not live anymore.

**Expected behavior**
A GitHub page with examples should open

**Version**
11.4.0-0

**Screenshots**
Link in the documentation:  
![image](https://user-images.githubusercontent.com/51883613/109761541-311c6000-7c16-11eb-9628-4e1f8004ba48.png)

**Comment by tommoor** [comment]
Thanks, you can view all the examples by clonining and running `yarn && yarn start`

**Comment by thoughtlessmind** [comment]
yes. I've cloned and ran the code and viewed the storybook demos.  

Is there any method to assign a higher `zIndex` to the tooltip wrapper? For the moment I've used the class assigned to the tooltip wrapper which is `.sc-gsTCUz` and gave a z-index from the root CSS file. Is there any other efficient way?  
Please pardon me as this question is quite different off from the issue.

**Comment by tommoor** [comment]
> Is there any method to assign a higher zIndex to the tooltip wrapper?

No, if you need that you're probably building your tooltips wrong. I'd recommend using a library or `react-portal` that moves the tooltips to the end of the dom to ensure they appear ontop of other items.

**Comment by tommoor** [comment]
doc updated to remove reference
