### ISSUE TITLE
Pasting bullet point list doesn't format as list

### ISSUE THREAD

**Issue by albinekb** [outline/rich-markdown-editor#4]
### To reproduce:
Copy and paste this:
```
- Bananas are great
- Outline is cool
- Open source rocks
```
Into the editor

### What happens?
Editor does not pick up the list as a list:
![image](https://user-images.githubusercontent.com/5027156/40735760-4a91c9c0-643c-11e8-8232-6e6d7fba7824.png)

### Expected
List is formatted as markdown list:
![image](https://user-images.githubusercontent.com/5027156/40735778-5ba8c1d2-643c-11e8-84fa-30dba9ed0196.png)

**Comment by tommoor** [comment]
I think this is a more general issue with all Markdown syntax, nothing is picked up on paste. I think the general approach to fixing this should be to get the paste contents and run it through `slate-md-serializer` - the resulting Slate document can be inserted as a fragment at the correct place.
