### ISSUE TITLE
Previous node gets transformed

### ISSUE THREAD

**Issue by aulneau** [outline/rich-markdown-editor#401]
Hi there -- 

This bug might not be specific to the editor, as I'm doing some yjs collaboration stuff with my application. I've noticed that when inserting a new node, the previous node becomes transformed to be whatever was inserted:

![broken editor](https://user-images.githubusercontent.com/11803153/110853642-7d504b80-8279-11eb-8a11-4e70a4be0df2.gif)

**Expected behavior**
The new node should take on the line it was inserted, not the closest one.

Any suggestions on where I might look to fix this behavior? 🙏

**Comment by tommoor** [comment]
You have the wrong version of `prosemirror-transform` installed, see this discussion for the solution:

https://github.com/outline/rich-markdown-editor/issues/261#issuecomment-686201757

**Comment by aulneau** [comment]
@tommoor yes that fixed it, thanks for your swift reply.

Is this an issue in the prosemirror lib that should be fixed? or will the editor forever be tied to 1.2.5?

**Comment by tommoor** [comment]
I've so far been unable to pindown the change in `prosemirror-transform` that causes this behavior, but nothing is forever.
