### ISSUE TITLE
Module not found: Can't resolve 'styled-components'

### ISSUE THREAD

**Issue by herbievine** [outline/rich-markdown-editor#405]
Here is my component: 

```
const MarkdownEditor: React.FC<MarkdownEditorProps> = ({}) => {
    return (
        <div className="flex flex-col items-start justify-start w-5/6 h-full z-10 absolute top-14 bg-gray-100">
            <Editor
                onChange={(val) => console.log(val)}
                defaultValue="Hello world!"
            />
        </div>
    )
}
```

**Note:** I am using SSR with Next.js

**To Reproduce**
Use the editor in next.js

**Expected behavior**
An editor is supposed to appear and log the change

**Version**
Editor: ^11.4.1
Next: latest (12/03/2021)
React: ^17.0.1

**Screenshots**
![image](https://user-images.githubusercontent.com/41120535/110973862-b958de80-8355-11eb-82d2-e5ab4f85162e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome
 - Version: Chrome Version 88.0.4324.190

**Smartphone (please complete the following information):**
N/A

**Comment by tommoor** [comment]
Hi, unfortunately this component will not work with SSR – it requires the dom, you might be able to use with a placeholder component. `styled-components` is a peer dependency, as noted in the install instructions:

https://github.com/outline/rich-markdown-editor#usage
