### ISSUE TITLE
Unordered and ordered lists have invisible bullets in Firefox

### ISSUE THREAD

**Issue by growandwin** [outline/rich-markdown-editor#416]
**To Reproduce**
1. git clone https://github.com/outline/rich-markdown-editor.git
2. npm install
3. yarn start
4. Open Firefox
5. Goto http://localhost:6006/?path=/story/editor--lists 

**Expected behavior**
Ordered and unordered lists should have visible bullets in firefox

**Version**
11.6.0

**Screenshots**
![lists](https://user-images.githubusercontent.com/41911497/112170564-728ba400-8bf3-11eb-8f1b-7140d7c36b91.PNG)

**Desktop:**
 - OS: Windows 10 PRO up to date
 - Browser Firefox Version 86.0.1
 - Tested on private window without extensions

On Chrome both lists render correctly.

**Comment by tommoor** [comment]
Damn it Firefox, confirmed 👍

**Comment by growandwin** [comment]
That fix was blazzing fast! Nice job!
