### ISSUE TITLE
Peer dependency requirements of upstream library prevents install of this library with React 17 without use of --force

### ISSUE THREAD

**Issue by brianbancroft** [outline/rich-markdown-editor#418]
- `react-medium-image-zoom` requires the use of React 16 ([link](https://github.com/tommoor/react-medium-image-zoom/blob/master/package.json#L79))

**To Reproduce**
(from the command line)
1. `npx create-react-app myapp && cd myapp`
2. `npm i rich-markdown-editor@latest`

**Expected behavior**
It installs

**Actual behavior**
It doesn't install unless developer includes `--force` flag on all installs.

```sh
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.2
(... glossing over this part for now)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.4.0" from react-medium-image-zoom@3.1.2
npm ERR! node_modules/rich-markdown-editor/node_modules/react-medium-image-zoom
npm ERR!   react-medium-image-zoom@"^3.0.16" from rich-markdown-editor@11.6.0
npm ERR!   node_modules/rich-markdown-editor
npm ERR!     rich-markdown-editor@"11.6.0" from the root project

```

**Version**
latest

**Desktop (please complete the following information):**
- MacOS, node 14.16.0

**Comment by tommoor** [comment]
#240 and #241 both necessitate upgrading this dependency too, sounds like the time is nigh.
