### ISSUE TITLE
Opt-out of toolbars

### ISSUE THREAD

**Issue by pierre-elie** [outline/rich-markdown-editor#42]
I see you've added options to the theme to selectively hide toolbar buttons, that's great 🎉 

Is there a quick way to opt out of toolbars entirely? I haven't spotted one.
Changing the theme to hide all toolbar buttons doesn’t help, it just displays empty toolbars.

I can try to submit a PR for the change, although not sure where it would make most sense: as a theme option or as a React prop?

**Comment by tommoor** [comment]
Hey @pierre-elie I'm going to close this for now, this is not trying to be an editor for everyone – it's quite opinionated and made for use in the Outline project, if it works for you great, if not then a more flexible editor such as CK might make sense :)
