### ISSUE TITLE
Editor instance throws a RangeError: Position -1 out of range if rendered within a <li> element

### ISSUE THREAD

**Issue by raunaqgupta** [outline/rich-markdown-editor#420]
Instantiating the editor within a `<li>` element throws the error:

```
RangeError: Position -1 out of range
```

**To Reproduce**
1. Instantiate the editor within a `<li>` element
2. Mouseover the editor

**Expected behavior**
The editor should be editable (if `readOnly` is set to `false`).

**Version**
11.0.10

**Screenshots**
![image](https://user-images.githubusercontent.com/623670/112699640-86c8de80-8e49-11eb-9c27-232c691db047.png)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser: Safari
 - Version: 14.0.3

**Notes**
- This error is possibly being caused by the DOMEvent handling here: https://github.com/outline/rich-markdown-editor/blob/45d97fe0c64a529e4215442ef16ed0d891970d88/src/nodes/ListItem.ts#L56
- Error disappears when `<li>` is replaced with a `<div>` element.

**Comment by tommoor** [comment]
Is the LI the direct parent of the editor or just somewhere up the tree?

**Comment by raunaqgupta** [comment]
> Is the LI the direct parent of the editor or just somewhere up the tree?

Several (> 1) levels above the editor instance.
