### ISSUE TITLE
On clicking same tag again in the popover it's property changing

### ISSUE THREAD

**Issue by karthick3018** [outline/rich-markdown-editor#444]
**To Reproduce**
1. Insert a h1 tag element 
2. Type some text
3. Select the text you've typed 
4. A popover will appear with some editing options select H1 option. You'll get the error as you can see the property is changing 

**Expected behavior**
Property of the tag should not change . 
**Version**
11.0.10
**Screenshots**
![image](https://user-images.githubusercontent.com/47154512/117264196-a0aa0800-ae70-11eb-8dd7-11a81d748456.png)
after selecting the H1

![image](https://user-images.githubusercontent.com/47154512/117264401-d2bb6a00-ae70-11eb-98fc-8db9943e87c2.png)

**Desktop (please complete the following information):**
 - OS: Macos bigsur
 - Browser :chrome
 - Version: 90.0.4430.93

**Comment by tommoor** [comment]
I'm sorry, I don't understand the issue you've filed – this seems like expected behavior – the buttons act as a toggle.

**Comment by karthick3018** [comment]
Hi @tommoor  https://www.loom.com/share/62f73c27bafc4b7f9592c0544471bb97 here is the video link

**Comment by tommoor** [comment]
Thank you for taking the time to make that.

I can confirm this is expected behavior otherwise there would be no way to turn an H1 back into a regular paragraph. It's very typical in editors for buttons like these to be toggles.
