### ISSUE TITLE
Codeblock adds additional characters

### ISSUE THREAD

**Issue by Valiantiam** [outline/rich-markdown-editor#447]
When you delete a character on a codeblock fresh line, it adds that character to the end of the line repeatedly for each additional character you type.

**To Reproduce**
1. Make a codeblock
2. Type a single character on its own line.
3. Backspace and replace it with a different letter.
4. It now starts putting copies of the original letter on that line for every character you type.

**Expected behavior**
It should not add additional characters.

**Screenshots**
![CodeblockProblem](https://user-images.githubusercontent.com/5394853/117319424-e8b93280-ae50-11eb-9962-85d3bf8c265e.gif)

**Desktop (please complete the following information):**
 - OS: [W10]
 - Browser [Chrome]
 - Version [90.0.4430.93 x64]

**Comment by tommoor** [comment]
wild, It's something to do with the `Prism` plugin – disabling highlighting on the block causes the bug not to reproduce
