### ISSUE TITLE
No cursor on newlines

### ISSUE THREAD

**Issue by erquhart** [outline/rich-markdown-editor#45]
First off, thanks for this fantastic tool. I've spent many, _many_ hours ~~slaving over~~ delightedly working with Slate and Markdown in Netlify CMS ([integration if you're curious](https://github.com/netlify/netlify-cms/tree/3514bc5e0bc22ee8942265c72c85da081f46b572/packages/netlify-cms-widget-markdown/src)), and was hoping to find a drop-in solution like this for a separate project. Was quite glad to find it!

I've noticed the cursor isn't visible on newlines, whether in the empty editor or after pressing enter. This isn't the case in Outline, but it is when the Editor component is loaded by itself.

Repro here: https://codesandbox.io/s/1o0mkrv2pl

Any thoughts?

**Comment by erquhart** [comment]
Found it: https://github.com/outline/rich-markdown-editor/commit/d87a2a9aaf19cf9bb0d36aa8ae385af33ef64dc5

Setting that back to `inline` fixes it.

**Comment by jorilallo** [comment]
Can confirm, I have this fix as well applied

--
Jori Lallo

+358-50-910 5555
jtlallo@gmail.com
http://about.me/jorilallo

Sent via Superhuman iOS ( https://sprh.mn/?vip=jtlallo@gmail.com )

**Comment by erquhart** [comment]
Considering that this fix targets a Slate classname that isn't a part of their API, it's likely to cause unexpected bugs. Have you opened an issue in Slate for the unexpected newlines problem? A proper fix could probably happen there.

**Comment by tommoor** [comment]
Yep – I removed the offending class in the last patch release as this bug is worse than the one I was intending to fix with the class in the first place.

**Comment by erquhart** [comment]
Ah, gotcha 👍
