### ISSUE TITLE
Table in  ordered list, lost order after saving

### ISSUE THREAD

**Issue by 4-1-1** [outline/rich-markdown-editor#451]
**To Reproduce**
1. open editor with content like 
```markdown
1.  abc

    | a | b |
    |--|--|
    |a1|b1|
2.  abc

    | a | b |
    |--|--|
    |a1|b1|
```
2. any modify and click save
3.  reopen it, and the list order is set to 1 

**Version**
11.8.1

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Comment by tommoor** [comment]
Table within an ordered list isn't really something we support, but I guess it should either be supported or prevented – not result in buggy behavior :)

**Comment by 4-1-1** [comment]
In my case , The file content is not write by this editor. It is prevented @tommoor

**Comment by tommoor** [comment]
Please see the note here: https://github.com/outline/rich-markdown-editor#rich-markdown-editor

This library is not aiming to render any arbitrary markdown, it will render markdown produced by the editor itself. I recommend that you sanitize the markdown before providing to the editor.
