### ISSUE TITLE
File data on uploadImage is not present

### ISSUE THREAD

**Issue by calixo888** [outline/rich-markdown-editor#454]
When I try to print the file being passed into `uploadImage` it doesn't give the data of the file to upload, and also throws an uncaught error right after.

**My Code**
```
<Editor
  defaultValue={initialValue}
  onChange={handleChange}
  uploadImage={async file => {
    console.log("file", file);
  }}
/>
```

**Expected behavior**
I expect to receive the file data upon upload so that I can upload it to my file provider.

**Version**
Currently using v11.8.1

**Screenshots**
<img width="394" alt="Screen Shot 2021-05-20 at 10 07 14 PM" src="https://user-images.githubusercontent.com/47236374/119085385-84ea4a00-b9b8-11eb-96b8-f3fa5f83c0e0.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by tommoor** [comment]
It's a native [File](https://developer.mozilla.org/en-US/docs/Web/API/File) object – see the outline codebase for an example of how to deal with it:

https://github.com/outline/outline/blob/main/app/components/Editor.js#L62-L68

**Comment by tommoor** [comment]
Closing because this API is for sure working, the error is because you didn't return a string from the method that represents the uploaded file location. Feel free to reply still.

**Comment by calixo888** [comment]
@tommoor do I need to use the `React.useCallback` function? For context I'm using SSR with Next.js, so I'm not sure if that has any effect on the data received. I tried accessing `file.file` and I got undefined.

Thank you for clearing up on the error though, that makes sense!

**Comment by tommoor** [comment]
I forget why (it should be commented), but it seems like the browsers behave differently:

https://github.com/outline/outline/blob/505ed3403a60047f2bdfbce47b41b8373b1ada3a/app/utils/uploadFile.js#L35-L40

You should see the [native documentation](https://developer.mozilla.org/en-US/docs/Web/API/File) for the various ways to deal with the File object.

**Comment by calixo888** [comment]
Is there a different browser I should be using then? I'm using Chrome but I don't think that's the reason. I tried looking through the native docs but couldn't find anything useful - would you recommend trying some specific functions?
