### ISSUE TITLE
Newline at the start of h2 results in error

### ISSUE THREAD

**Issue by xypnox** [outline/rich-markdown-editor#457]
When we add a line break at the start of h2 the editor panics.

**To Reproduce**

1. Go to a second level heading.
2. Add a line break.

**Expected behavior**
The heading should split like in h1.

**Version**
v11.9.0 inside Electron

**Screenshots**

https://user-images.githubusercontent.com/25076171/119365881-05b58880-bcce-11eb-8474-339649ad53d9.mov

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Electron
 - Version: 11.0.1

**Comment by tommoor** [comment]
I've been unable to reproduce this unfortunately

**Comment by xypnox** [comment]
I linked the `rich-markdown-editor` as a local package via `yarn link`, and It solved the issue. 
However, I don't have clear idea why. 

I am closing the issue as it has been resolved for me.
