### ISSUE TITLE
Syntax Highlighting not working on `<code />`

### ISSUE THREAD

**Issue by ScottAgirs** [outline/rich-markdown-editor#458]
Syntax highlighting works neatly on `<pre />` tags, but leaves the `<code />` seemingly unaffected.

**Expected behavior**
Highlighting to be applied on both `<pre />` as well as `<code />` 

**Version**
`rich-markdown-editor: 11.9.0`

**Screenshots**
### **With `rich-markdown-editor`**
<img width="534" alt="Screen Shot 2021-05-24 at 10 56 44 AM" src="https://user-images.githubusercontent.com/11737572/119366228-bdbb4500-bc7e-11eb-9a4d-ee8838a0b775.png">

### **With other parser**
<img width="666" alt="Screen Shot 2021-05-24 at 10 57 26 AM" src="https://user-images.githubusercontent.com/11737572/119366322-d4fa3280-bc7e-11eb-847a-acd790bb4527.png">

**Comment by tommoor** [comment]
Hey Scott, thanks for filing. This is expected behavior – we've chosen not to highlight syntax because this monospaced treatment is used for more than just code and adding the UI for choosing language here would be very difficult to achieve as these marks can be so small.
