### ISSUE TITLE
Floating toolbar gets covered by native toolbar on text selection in android

### ISSUE THREAD

**Issue by drishit96** [outline/rich-markdown-editor#462]
Floating toolbar gets covered by native toolbar on text selection in android

**To Reproduce**
Step to reproduce the behavior:
1. Select any text in the editor

**Expected behavior**
The floating toolbar should be fully visible

**Version**
11.9.1

**Screenshots**
![toolbar](https://user-images.githubusercontent.com/13049630/120223439-39108e00-c25f-11eb-8515-8f05503352d4.png)

**Smartphone (please complete the following information):**
 - Device: Nokia 5.1 Plus
 - OS: Android 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Comment by tommoor** [comment]
@drishit96 any thoughts on how other apps on Android handle this?

**Comment by drishit96** [comment]
In [Notion](https://notion.so), the android app handles this beautifully by showing a toolbar atttached to the top of the keyboard (or at the bottom of the page).
![notion_ss](https://user-images.githubusercontent.com/13049630/120526766-347edd80-c3f7-11eb-9641-6222bc12d98e.png)

However, their web app (on android) doesn't show any kind of toolbar at all, which is kind of weird because on desktop it shows a similar floating toolbar like outline.

**Comment by tommoor** [comment]
A bottom-fixed toolbar came to mind for me too, if there's a reliable way to position this (there should be!) then I think this would be a good improvement for mobile across all platforms

**Comment by drishit96** [comment]
I think positioning the toolbar using `position: fixed;  bottom: 0` should work.
