### ISSUE TITLE
Resetting state

### ISSUE THREAD

**Issue by erquhart** [outline/rich-markdown-editor#47]
Any interest in adding a method for resetting the state of the editor (to `defaultValue` or empty string, just like at load)? Dynamic import is the only way at the moment, but it'd be nice for a single instance to be able to reset on the fly, eg. when switching to a different entry.

**Comment by jorilallo** [comment]
You can do this easily by using a different key prop on the editor (eg entry id)

--
Jori Lallo

+358-50-910 5555
jtlallo@gmail.com
http://about.me/jorilallo

Sent via Superhuman iOS ( https://sprh.mn/?vip=jtlallo@gmail.com )

**Comment by tommoor** [comment]
Hey @erquhart – as Jori mentioned the current React best practice would be to change the `key` prop on the react component, this is how we do it in Outline. I do think there would be value in a `reset` method being exposed if you'd like to take a stab though 😄

**Comment by erquhart** [comment]
Awesome, learned something new today! Resetting state via key should work fine, thanks.
