### ISSUE TITLE
`onClickLink` not working

### ISSUE THREAD

**Issue by sklinov** [outline/rich-markdown-editor#478]
**To Reproduce**
1. Go to https://codesandbox.io/s/rich-markdown-editor-kbbyu?file=/src/App.tsx
2. See that `wikipedia` link is recognized as a link, but the cursor is not changed on hover.
3. Click on 'http://wikipedia.org'
3. See that nothing happens.

In some other cases (like in my main project), `onClickLink` is not being invoked, but the link is clickable and shows default behavior.
UPD: when updated from v. 11.7.0 to 11.12.0-0 `onClickLink` started working only with `command` button pressed

**Expected behavior**
Invoke `onClickLink` function and follow its instructions when clicked on a link.

**Version**
11.12.0-0

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 91.0

**Comment by tommoor** [comment]
The link you shared doesn't include the content, but `onClickLink` is only triggered in `readOnly` mode currently, this should be documented. It becomes difficult to edit a link if clicking on it opens it when editing, but if a good pattern can be found to enable both I'd accept a PR.

**Comment by sklinov** [comment]
@tommoor Sorry about that, looks like autosave wasn't turned on.
Thanks for your comment about `onClickLink`, I'll think of a workaround for my case then.
