### ISSUE TITLE
Table option not in the menu 

### ISSUE THREAD

**Issue by TcM1911** [outline/rich-markdown-editor#479]
Table option in the menu is missing.

**To Reproduce**
1. Type / or click the + button.
2. Scroll down to Quote.
3. Table option should be above the Quote option.

**Expected behavior**
An option to create a new table in from the menu. It is possible to paste in a markdown table. It parses it fine and you can modify it.

**Version**
11.11.1

**Screenshots**
![image](https://user-images.githubusercontent.com/7453350/122814589-52d84a80-d2cc-11eb-8f60-a8165e6443d6.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser firefox and safari

**Comment by tommoor** [comment]
closed by c4b81e711f5207707cb956f75693b5ca37145911
