### ISSUE TITLE
Allow paste from Google Docs

### ISSUE THREAD

**Issue by olehmell** [outline/rich-markdown-editor#483]
### Discussed in https://github.com/outline/rich-markdown-editor/discussions/482

<div type='discussions-op-text'>

<sup>Originally posted by **olehmell** June 25, 2021</sup>
When I paste to ProseMirror all good:

![image](https://user-images.githubusercontent.com/39906111/123430832-4c4e1980-d5d1-11eb-9f8c-efb9cdbc1ed9.png)

But when paste to rich-markdown-editor on my app, this looks like a plain text:

![image](https://user-images.githubusercontent.com/39906111/123431052-84edf300-d5d1-11eb-9001-29884b025266.png)

Have any idea how I paste text from Google Docs with saving struct documents?
Maybe I can write a custom handle for the HTML paste event?</div>

**Comment by tommoor** [comment]
Apologies for late reply, classing this as a bug – it really should understand the html on the pasteboard.
