### ISSUE TITLE
Getting exception on android webview 

### ISSUE THREAD

**Issue by nikita2423** [outline/rich-markdown-editor#485]
I have used this library, it is working on web but when I try to run in android web-view it is throwing an exception 

next: 10.2 
"rich-markdown-editor": "^11.13.0"

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

![WhatsApp Image 2021-07-01 at 6 55 49 PM](https://user-images.githubusercontent.com/16168752/124133098-1c09ed80-da9f-11eb-9279-14a1a0afa414.jpeg)

**Smartphone**
 - Device: Android 
 - OS: Android
 - Browser : Android WebView

Did anyone encounter the same issue? Is there any solution ?

**Comment by tommoor** [comment]
Please add details of what the actual error is in javascript, thanks
