### ISSUE TITLE
Images pasted into table cells don't serialize in markdown

### ISSUE THREAD

**Issue by RuslanGabbasov** [outline/rich-markdown-editor#489]
As I understood, images can't be used in tables cells now, but they could be pasted from the clipboard into the cell and lost while serializing to markdown:
![Kooha-2021-07-06-11 58 31](https://user-images.githubusercontent.com/20418709/124556674-00616700-de52-11eb-93cc-cafd5f01b386.gif)

**Comment by sztanko** [comment]
Neither do embeds
