### ISSUE TITLE
Sanitize markdown

### ISSUE THREAD

**Issue by jfrolich** [outline/rich-markdown-editor#49]
The markdown output currently is not great where it needlessly escapes a lot of characters, for instance a `.` will become `\.`. Just putting this on the radar. When using the raw markdown somewhere else for instance when exporting, this is not great.

**Comment by tommoor** [comment]
We've got an ongoing project in the serializer library to tackle this, https://github.com/tommoor/slate-md-serializer/commits/master/src/utils.js

We're definitely playing it safe right now – It's important that you could write something that looks exactly like markdown in the editor and it should be reproduced faithfully on reload.
