### ISSUE TITLE
Pressing enter in an empty nested list item creates several more empty list items

### ISSUE THREAD

**Issue by seeruk** [outline/rich-markdown-editor#497]
If you make a nested list, something like this:

```
* Hello
* World
  * Nested
  *
```

Then hit enter in that last empty item, you end up with something like this:

```
* Hello
* World
  * Nested
* 
*
  *
```

Note, this also happens in further nested lists, it just produces the same 3 empty nodes 1 level of nesting higher than the level you were at when you hit enter on the initial empty list item.

**To Reproduce**
1. Enter the first markdown structure seen above
2. Hit enter in the empty (last) list item
3. See error

Edit: It also looks like you need to specify prosemirror-transform 1.2.5 in resolutions for this issue to occur, but a fresh install in a CRA project also exhibits these symptoms with the resolutions applied.

<details>
  <summary>My package.json for the fresh CRA project</summary>
  
```json
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "resolutions": {
    "prosemirror-transform": "1.2.5"
  },
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.56",
    "@types/react-dom": "^16.9.12",
    "react": "^16.14.0",
    "react-dom": "^16.14.0",
    "react-scripts": "4.0.3",
    "rich-markdown-editor": "^11.14.0",
    "styled-components": "^5.3.0",
    "typescript": "^4.1.2",
    "web-vitals": "^1.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```
</details>

**Expected behavior**
It should probably step back up in list levels until it's at the top level then revert to an empty paragraph after that. 

**Version**
11.14.0

**Screenshots**
Before:
<img width="584" alt="Screenshot 2021-07-17 at 23 06 03" src="https://user-images.githubusercontent.com/2083033/126050356-e4f69e63-64d9-4437-8631-f1d7e81d1fb5.png">

After:
<img width="593" alt="Screenshot 2021-07-17 at 23 11 35" src="https://user-images.githubusercontent.com/2083033/126050360-e811f9f7-9aa7-4161-b42e-a497e660749c.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.4
 - Browser: Chrome
 - Version: 91.0.4472.114

**Smartphone (please complete the following information):**
N/A / not tested there

**Comment by seeruk** [comment]
Seems to be linked to #427 actually. I've removed the resolutions I added for prosemirror-transform and that fixes this list issue, but then I'm back to having the issue described in #427 with headings affecting the line above or below.

**Comment by tommoor** [comment]
Thanks for providing the follow up 👍 

I've also added the "prosemirror-transform" resolution inside this package in the hopes to prevent future reports until compatibility is achieved.
