### ISSUE TITLE
Using as a Controlled Component

### ISSUE THREAD

**Issue by ecumene** [outline/rich-markdown-editor#517]
https://reactjs.org/docs/forms.html#controlled-components

**To Reproduce**
```
const [value, setValue] = useState();
return <Editor value={value} onChange={(getChanges) => setValue(getChanges())}
```

Typing any letters makes the cursor jump back to the start of the document, writing backwards

**Expected behavior**
I expect using `Editor` as a controlled component to work. The reason I want this is that I want to be able to clear the text box after you submit.

**Version**
latest

**Desktop (please complete the following information):**
 - OS: Pop!_OS
 - Browser Firefox/Chrome
 - Version Latest Stable
 

What's the best way to clear the text in the meantime? Is there a way to access the ProseMirror object underneath via a ref somehow?

**Comment by tommoor** [comment]
Changing the `value` prop completely resets the state which includes the selection state. The answer is to not use it as a controlled component in this way, it's not within scope of the project to change this behavior.

I recommend adding a `key` prop that you change on submission to remount the editor for the usecase you've described

**Comment by ecumene** [comment]
Have you considered adding a `ref` for the inner Prose context so I could clear it that way?

**Comment by tommoor** [comment]
You should be able to access everything prosemirror related through the existing ref, `ref.view.state`
