### ISSUE TITLE
Keyboard shortcuts on first line

### ISSUE THREAD

**Issue by gscoon** [outline/rich-markdown-editor#53]
I love what you've built here.  

Problem:
Keyboard shortcuts (like **bolding**) do not activate marks on the first line of the editor.  However, clicking "bold" from the toolbar seems to work.  The shortcuts only seem to work after going to new line.

**Comment by gscoon** [comment]
I see now that this is intentional (below).  Would be great if this could be controlled using the editor options
```js
toggleMark: function toggleMark(change, type) {
      var value = change.value;
      // don't allow formatting of document title

      var firstNode = value.document.nodes.first();
      if (firstNode === value.startBlock) return;

      change.toggleMark(type);
    },
```

**Comment by tommoor** [comment]
@gscoon thanks for the note – yea, this was kind of left over from the usage inside of https://github.com/outline/outline . It can be removed but I'll need to figure out a strategy to still prevent the toolbar in Outline.
