### ISSUE TITLE
Extra line beneath the image after uploading

### ISSUE THREAD

**Issue by wcjx** [outline/rich-markdown-editor#537]
As can be seen, there is an extra line between the image and the new paragraph after uploading an image.
![image](https://user-images.githubusercontent.com/43997506/131244976-1fbbd889-e81c-4192-81e6-2597c57b7e12.png)
Typing in this line, block menu shows up in the right top corner of the image, which is weird. The text node in this line has the same parent paragraph node as the image.
![image](https://user-images.githubusercontent.com/43997506/131245127-6bcdec1a-075d-4aa2-aef6-ee8f7ff18cf9.png)
Another effect is that it takes two backspaces to delete this image after uploading.

**To Reproduce**
Just upload an image

**Expected behavior**
Setting image node schema as  `group: "block"` can remove this line. This is more intuitive.
![image](https://user-images.githubusercontent.com/43997506/131245476-aacb0c3e-0372-4368-8470-5f32f64c8180.png)

**Version**
11.17.3

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome 92

**Comment by tommoor** [comment]
Unfortunately changing images to block nodes breaks many other behaviors and expectations of how images layout. Hopefully this can be addressed with css
