### ISSUE TITLE
Folded headers prevent newline creation

### ISSUE THREAD

**Issue by haveanicedavid** [outline/rich-markdown-editor#538]
When using folded headers on a newly added header, trying to create a new line from the folded header doesn't behave as expected. New lines are created, but they're appended to the folded content and don't show until opening. Cursor position stays on the header, and keyboard navigation breaks

**To Reproduce**
1. Create a header with some content underneath
2. Fold that header
3. Click to end of line on the header and hit enter
4. Cursor will not move, and typing will append to the current header line

**Expected behavior**
Ideally, the folded header would properly maintain its content, a new line would be created, and the cursor would be placed there (so it would behave like a normal document without the folded content). 

**Screenshots**
https://www.loom.com/share/816c1dc8b41e48a6ab49a6995801b0d5

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome & Safari
 - RME Version 11.17.2

**Comment by tommoor** [comment]
Thanks for the solid bug report, agreed in expected behavior

**Comment by tommoor** [comment]
Looking at fixing this, but there is some awkwardness – because any content beneath the heading and before the next heading is automatically collapsed even if you place the new paragraph at the end instead of the beginning it's still invisible.

I'm beginning to think the answer is to auto-expand the header in this scenario.

**Comment by haveanicedavid** [comment]
@tommoor Just seeing this - I was poking through the codebase last night trying to brainstorm. 

I'm not sure how this would fit with Outline, but for my use case what would be great is to have newline creation on collapsed headers default to creating a new header.

So if my cursor (`|`) is at the end of a collapsed header:
```
# Collapsed Header  |
```
and I hit enter, instead of creating a paragraph mark ie
```
# Collapsed Header
Paragraph text which is under nested header (and thus hidden in the dom)
```
it would create another header of the same depth (ie h1 => h1, h2 => h2): 
```
# Collapsed Header
# Newly created line
```

The UX makes a lot of sense to me, because the only situation I would create a newline from a collapsed header is to create another header at the same depth - like to hide away content while I'm producing a larger document.

What do you think?

**Comment by tommoor** [comment]
I think this is a great solution, not sure why I didn't think of it 😉
