### ISSUE TITLE
How to set focus on the end of rich-markdown-editor

### ISSUE THREAD

**Issue by scottge** [outline/rich-markdown-editor#54]
Hello

How can I set focus on the end of the end of rich-markdown-editor?  I want to implement something similar to your 'ClickablePadding' component in the outline production website.  User clicks on the padding area, and the focus is automatically set on the end of the editor.

**Comment by tommoor** [comment]
There is a `focusAtEnd` method exposed on the component for this usecase:

https://github.com/outline/rich-markdown-editor/blob/master/src/index.js#L208
