### ISSUE TITLE
Image format is not working in the latest version 11.17.9

### ISSUE THREAD

**Issue by Aaron-Hu** [outline/rich-markdown-editor#551]
This issue can be reproduced in  11.17.9, but works fine in 11.17.6

**To Reproduce**
Version 11.17.9, click an image, and there is no format popup
![image](https://user-images.githubusercontent.com/19277713/134610688-f60adfa3-cf1c-4b2c-9d99-85a8f918c0cd.png)

Version 11.17.6 works fine
![image](https://user-images.githubusercontent.com/19277713/134610496-9edd3223-2971-46cf-a313-a4a27985b8d3.png)

**Comment by tommoor** [comment]
Same issue as #550 fixed in latest patch 😄
