### ISSUE TITLE
Blank line misinterpreted as a new paragraph

### ISSUE THREAD

**Issue by scottge** [outline/rich-markdown-editor#56]
The control seems to misinterpret blank line as a new paragraph.  For example, 

```
const str = `
Paragraph 1

Paragraph 2`

<RichMarkdownEditor
     defaultValue={str}
/>
```

This results in a 3rd paragraph between 'Paragraph 1' and 'Paragraph 2' in the editor.  
I'm using github md css to style the output of RichMarkdownEditor.  This additional paragraph doubles the space between each paragraph.

**Comment by tommoor** [comment]
Hi @scottge, this is actually by design. Paragraphs are not collapsed together as is typical in markdown as this would make it impossible to have multiple blank lines inbetween paragraphs – a common usecase.

I recommend reducing the margin/padding between paragraphs to reduce the space as the example css.

**Comment by scottge** [comment]
Thank you for your prompt reply, particularly on New Year day! 

This appears to break the markdown format because typical markdown requires at least one blank line between paragraphs.  

The same problem happens when I save the content edited in RichMarkdownEditor to a .md file:  Imagine that the user uses your editor to create 2 paragraphs, and saves it to a .md file.  The resulting .md file will have NOT have the extra blank line between the two paragraphs.  When the .md is displayed in other sites (e.g. github), the two paragraphs would display as one paragraph.

**Comment by tommoor** [comment]
The key is to style the paragraphs with no margin between them – the output will then look the same as it does in the editor. Unfortunately the markdown spec is not 100% compatible with a rich text editor so this is one of the compromises that had to be made.

Take a look at how the editor css is put together on http://www.getoutline.com – the main consumer of this library.

**Comment by scottge** [comment]
However, this issue makes the .md produced by your editor component incompatible with any other .md display control.  Multi-paragraphs produced by your editor will be interpreted as one single paragraph in any other industry md controls. 

Is there any chance that you could provide a prop in your component to optionally respect the 'blank line' standard, or could you point me to the code that does not magic, and I will try to fix it (for myself).
