### ISSUE TITLE
Adding a blank line to create a list after Heading

### ISSUE THREAD

**Issue by aquibbaig** [outline/rich-markdown-editor#565]
I love the design of the editor and I tried it out to check if everything works. I found out that when I insert a Heading and press enter to create a list, the editor is still in the context of the Heading and it doesn't insert a new list. For it to work as expected, I have to create a new paragraph or press enter twice, after that I can successfully insert a list or whatever I want to. Am I missing something here or this is an expected pattern?

Steps to reproduce: A simple instance of Editor, such as [this one](https://codesandbox.io/s/ecstatic-dhawan-oovo0?file=/src/App.js&resolutionWidth=320&resolutionHeight=675)

**Comment by tommoor** [comment]
I'm not sure I can reproduce the behavior you're seeing... make a quick screencast?

**Comment by aquibbaig** [comment]
@tommoor Here's one
https://user-images.githubusercontent.com/26324376/136682039-4cfc81d0-2fed-40f5-b492-94efe0af8c4f.mov

**Comment by tommoor** [comment]
I'm on mobile rn so can't point you to the exact thing but we've seen this issue many times - the incorrect version number of prosemirror-transform is installed

**Comment by aquibbaig** [comment]
I haven't installed `prosemirror-transform` in the sandbox, does the editor require it somewhere ?
