### ISSUE TITLE
Toggle todolist in new line with text after

### ISSUE THREAD

**Issue by piranhoid** [outline/rich-markdown-editor#581]
Hello ! 

When i click on the add button then tasklist, the following line is transformed, this behavior doesn't exist on Outline, how is it possible ? 

Exemple : https://www.loom.com/share/1bc336f13123453d81bdb80ea6303470

Code : https://codesandbox.io/s/confident-swartz-s7900?file=/src/styles.css

**Comment by tommoor** [comment]
Please see https://github.com/outline/rich-markdown-editor/issues/427#issuecomment-812577823
