### ISSUE TITLE
Content of an info notice spills outside container when content includes a code snippet

### ISSUE THREAD

**Issue by raldred** [outline/rich-markdown-editor#584]
Small rendering issue where adding a code snippet inside a notice causes the content to spill outside the notice container

**To Reproduce**
1. Create an info notice with some content that would wrap
2. Write a code snippet inside 
3. See content of notice spilling outside the container

**Expected behavior**
Content should be contained, code snippet should probably have horizontal scroll

**Version**
If known, what is the version of the module in use.
Present in outline v0.60.0

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

![image](https://user-images.githubusercontent.com/37096/141307731-52e5253f-9ba0-48f2-b068-4a4d4f2382f7.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 95

**Comment by tommoor** [comment]
Thanks for filing, seems like it'll be an easy css fix
