### ISSUE TITLE
Table will break if you click on table row action other than the first one

### ISSUE THREAD

**Issue by jxh0414com** [outline/rich-markdown-editor#595]
When you click on the first block, you can add additional rows

But when you click on the others it will break 
![image](https://user-images.githubusercontent.com/46506357/144070100-55250f62-cb65-4619-a77b-f82b667aa67c.png)

![image](https://user-images.githubusercontent.com/46506357/144070137-9319f347-70a4-48b0-8d0e-f02f4ee4a3bc.png)

**Comment by tommoor** [comment]
Double check the versions of dependencies installed, this doesn't seem to reproduce on the demo site which is built from `main`:

https://rich-markdown-editor-demo.onrender.com/?path=/story/editor--tables

**Comment by jxh0414com** [comment]
Oh sorry i was using the old version, my bad SORRY!@
