### ISSUE TITLE
Editor does not show nested lists correctly (bulleted in ordered)

### ISSUE THREAD

**Issue by mcholcha** [outline/rich-markdown-editor#596]
Editor does not show nested lists correctly (bulleted in ordered)

I am trying to add a bulleted list as a sublist of one of the ordered list items. The elements that I want to change to the bulleted list, do not change their appearance in the Editor. The generated markdown is correct.

To sum up:
In the Editor, a nested sublist looks like an ordered list.
In Markdown, the nested sublist is a bulleted list.

**To Reproduce**
https://user-images.githubusercontent.com/16899071/144246937-249b957a-845e-401e-a5e4-b681f8156ea1.mov

**Expected behavior**
In the Editor, the nested sublist should look like a bulleted list.

**Version**
11.20.1

**Desktop:**
 - OS: MacOs
 - Browser chrome
 - Version 94.0

**Comment by tommoor** [comment]
I suspect this is a css issue in your implementation, it does not reproduce on the demo site:

https://rich-markdown-editor-demo.onrender.com/?path=/story/editor--default

**Comment by mcholcha** [comment]
@tommoor 
You're right it's a css error. Sorry for wasting your time. Thanks for your help!
