### ISSUE TITLE
NextJS fails to compile due to global CSS dependency in node modules

### ISSUE THREAD

**Issue by gavindoughtie** [outline/rich-markdown-editor#598]
**To Reproduce**
Include the rich markdown editor component in a component rendered server-side by nextjs

**Expected behavior**

**Version**
12.0.0-beta.0
(using with React 18 beta)

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

`
./node_modules/katex/dist/katex.min.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/rich-markdown-editor/dist/nodes/Math.js
`

**Desktop (please complete the following information):**
OSX
 Chrome

**Smartphone (please complete the following information):**

**Comment by tommoor** [comment]
Please see this issue: https://github.com/outline/rich-markdown-editor/issues/303

The component does not support SSR at this time so you should ensure `window` is available.
