### ISSUE TITLE
Cannot create link in bullet point text

### ISSUE THREAD

**Issue by albinekb** [outline/rich-markdown-editor#6]
If I start typing or click the input field, the input goes away, see attached gif:

![kapture 2018-05-30 at 19 10 31](https://user-images.githubusercontent.com/5027156/40736038-28ab7eb8-643d-11e8-948f-e149de61f847.gif)

**Comment by tommoor** [comment]
Unfortunately, I've been unable to reproduce this so far copying exactly what you did in the gif above 😢.

It could be that an earlier JS error messed up the editor state…

**Comment by tommoor** [comment]
I reproduced this on the production version of Outline yesterday. Do you know if the gif you took above was from `rich-markdown-editor` or the Outline website? Might narrow it down.

**Comment by albinekb** [comment]
This was on the hosted outline website 👍 @tommoor

**Comment by tommoor** [comment]
Appears to be caused by the autosave causing the focus to change, so yea it's actually an Outline bug. I'll move it there.
