### ISSUE TITLE
Block Insert trigger is activated based on mouse location in window, not parent element

### ISSUE THREAD

**Issue by johnmcdowall** [outline/rich-markdown-editor#64]
If the intention is for this to be a somewhat general rich markdown component, the Block Insert trigger behaviour kinda prevents that, since it is [looking at mouse position in relation to the width of the window](https://github.com/outline/rich-markdown-editor/blob/master/src/components/BlockInsert.js#L58-L62) to trigger itself: 

```
    const windowWidth = window.innerWidth * 0.33;
    const result = findClosestRootNode(this.props.editor.value, ev);
    const newState = { ...this.state };

    newState.active = ev.clientX < windowWidth;
```

The assumption here is that the Editor will only ever be used in a circumstance where it's taking up the full page?

A more forgiving approach might be to just look and see if the mouse position is to the left of the target:

```
newState.active = result && ev.clientX < result.bounds.left;
```

This basically has the same behaviour as the window inner width calculation without behaving weirdly if the edit is used in a form, say. 

Happy to open a PR if it'll be accepted. 

Thanks!

**Comment by tommoor** [comment]
I don't think the behavior would be the same with that proposed solution however I don't disagree that it would be ideal to untie this from the window bounds…

The expected behavior is that as you move your mouse to the left of the editor (originally it was the left third, but could be the half) then the block input control would appear.

**Comment by omryr** [comment]
is there a solution for this situation? i want to implement this editor inside my website but in a page where it doesn't have the whole page, and the toolbar always gets absolutely positioned compared to the whole page as well as the Block Insert which also gets positioned compared to the mouse
