### ISSUE TITLE
Any plans to support markdown and/or jsx 

### ISSUE THREAD

**Issue by jmolivas** [outline/rich-markdown-editor#68]
There is any plan to provide support for `mdx` https://mdxjs.com/ ?

There is a roadmap for upcoming features?

Great project by the way ;)

**Comment by tommoor** [comment]
Hey, not sure what you mean by plans to support Markdown? All of the markdown standard works with the editor right now and the input / output is Markdown too 😉 

As for JSX, I don't think that's something we'll be supporting as it's a security risk for any environment where user input is untrusted. I believe you could probably add it as a plugin though!

**Comment by jmolivas** [comment]
My bad, wrong title supposed to say `mdx` not markdown ;)

Thanks for the reply
