### ISSUE TITLE
Cannot edit image caption

### ISSUE THREAD

**Issue by devincma** [outline/rich-markdown-editor#69]
Hi, 

Thanks for this excellent project. I have a question regarding the `Image.js` component. I was wondering since in the `schema`, `isVoid` is set to `true`, and we set `contentEditable={false}`, how come you can still edit the caption textarea on getoutline.com? I tried implementing the same thing, but when I set `isVoid: true`, I cannot enter caption in the textbox. Thanks!

**Comment by tommoor** [comment]
The caption is implemented as a textarea, see:
https://github.com/outline/rich-markdown-editor/blob/master/src/components/Image.js#L83-L94
