### ISSUE TITLE
Creating a link from an empty selection triggers an error

### ISSUE THREAD

**Issue by glaand** [outline/rich-markdown-editor#71]
At the canvas if you double-click at an empty starting line and select the link option, it triggers an error.

<img width="1429" alt="grafik" src="https://user-images.githubusercontent.com/17197309/54240692-116a6980-451f-11e9-9d72-f457f3a7d152.png">

The error is triggered by a TypeError
<img width="858" alt="grafik" src="https://user-images.githubusercontent.com/17197309/54240721-247d3980-451f-11e9-8a7d-46f01b1458c1.png">

**Comment by tommoor** [comment]
closed by https://github.com/outline/rich-markdown-editor/commit/3bc474b4b3dd376cb650b889cd71d2b761afd6ce
