### ISSUE TITLE
Why is this package using forked Slate plugins (e.g. @tommoor/slate-edit-list)?

### ISSUE THREAD

**Issue by Aerlinger** [outline/rich-markdown-editor#74]
It looks like most of the Slate plugins for this project are forks. For instance, the `@tommoor/slate-edit-list` plugin a few years behind its parent project `GitbookIO/slate-edit-list`. In fact, it looks like there are two forks of `slate-edit-list` which have more recently been maintained:

- https://github.com/productboard/slate-edit-list (Most recently updated)
- https://github.com/GitbookIO/slate-edit-list

(Same goes for the `slate-edit-code`, `slate-edit-blockquote`, and `slate-trailing-block` plugins).

I'm guessing the older `@tommoor/slate-edit-list` npm module is being used for legacy/compatibility reasons? If so, why was it forked in the first place? Is there any benefit of looking into using the more recent plugin versions?

**Comment by tommoor** [comment]
Gitbook forked their Slate implementation, it's no longer compatible with slate.js – the forks maintain compatibility. I'm not sure what makes you think the forks are older though, this was last updated less than a month ago:

https://www.npmjs.com/package/@tommoor/slate-edit-list
