### ISSUE TITLE
paragraph change to head1 if insert horizontal line after it.

### ISSUE THREAD

**Issue by hecor** [outline/rich-markdown-editor#78]
### Editing status:

![image](https://user-images.githubusercontent.com/1171710/56268972-2c835700-6125-11e9-8b0f-59545cde431e.png)

### After saving:
![image](https://user-images.githubusercontent.com/1171710/56268833-e5956180-6124-11e9-98f4-4f94cda2e71e.png)

But it will be fine if there is blank line between paragraph and horizontal line.

**Comment by smeijer** [comment]
That's part of the spec. It's the "alternative syntax" for headings.

https://daringfireball.net/projects/markdown/syntax#header

> HEADERS
> Markdown supports two styles of headers, `Setext` and `atx`.
> 
> Setext-style headers are “underlined” using equal signs (for first-level headers) and dashes (for second-level headers). For example:
> 
> ```
> This is an H1
> =============
> 
> This is an H2
> -------------
> ```
> 
> Any number of underlining =’s or -’s will work.
> 
> Atx-style headers use 1-6 hash characters at the start of the line, corresponding to header levels 1-6. For example:
> 
> ```
> # This is an H1
> 
> ## This is an H2
> ```

**Comment by hecor** [comment]
Thanks @smeijer , I wonder how can I disable this feature in our markdown parser. 
Thanks again.

**Comment by tommoor** [comment]
Great find, yea we need to disable that parser rule – should be easy enough
