### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by WNemencha** [outline/rich-markdown-editor#79]
It seems that currently this component doesn't supports SSR. We are using Next.JS internaly and would like to use this to display our blog posts, but we can't only rely on client-side rendering because that would defeat the whole point of using Next, that is SEO for free.

I will push a PR with SSR support soon, this issue is here to keep track of progress !

**Comment by tommoor** [comment]
Hey William, great! Looking forward to receiving your PR for this

**Comment by WNemencha** [comment]
@tommoor I've just pushed a PR, feel free to tell me if something needs to be changed to match the contributions guidelines or stuff. :stuck_out_tongue:

**Comment by kelvien** [comment]
Does SSR here mean that we can render the content in `defaultValue`/`value` props?

In the PR I only see changes within the `componentDidMount`, and if I understand SSR correctly in React, `componentDidMount` is not a part of a lifecycle that will be executed in SSR (`React.renderToString`). Can someone explain to me how the PR above enables SSR?

I am also trying to render my editor's content in the server-side, but it doesn't seem like it's supported yet. And I'm using rich-markdown-editor version `10.4.0`

**Comment by tommoor** [comment]
SSR just means that the component can be rendered on a server (no window object).

I'm not sure how it performs with rehydration - it's possible other fixes are needed, this isn't a usecase I've tested against personally.

**Comment by kelvien** [comment]
Got it. That is what I would expect too, but it doesn't seem like the Editor renders the initial values on server because the values initialization is done during `componentDidUpdate` which in SSR case, that lifecycle does not exist on server-side.

**Comment by kelvien** [comment]
Ah I think I see what's going on, I looked at the state of the Editor file on this [commit](https://github.com/WNemencha/rich-markdown-editor/blob/1cd3580df4c110f9a9f495fb9ccd0938c02e40d4/src/index.js#L79)
The value of the `StyledEditor` is defined in the [constructor](https://github.com/WNemencha/rich-markdown-editor/blob/2bef93037fee62d9ec0b2df2fb08d113ae5c83f1/src/index.js#L79)
Whereas in the latest version the value is defined in the `componentDidMount` hence it's never rendered in the server
