### ISSUE TITLE
LinkToolBar placeholder

### ISSUE THREAD

**Issue by adam15** [outline/rich-markdown-editor#85]
I couldn't find a way to change placeholder of link tool bar. Since it's a portal I can't find by document.getElementsByClassName so I can't change placeholder from there too. Is there any way to change this placeholder?
Here's the input (src/components/Toolbar/LinkToolbar.js): 
`       <LinkEditor>
          <Input
            ref={ref => (this.input = ref)}
            defaultValue={href}
            placeholder="Search or paste a link…"
            onKeyDown={this.onKeyDown}
            onChange={this.onChange}
            autoFocus={href === ""}
          />
          {this.state.isEditing && (
            <ToolbarButton onMouseDown={this.openLink}>
              <OpenIcon color={this.props.theme.toolbarItem} />
            </ToolbarButton>
          )}
          <ToolbarButton onMouseDown={this.removeLink}>
            {this.state.isEditing ? (
              <TrashIcon color={this.props.theme.toolbarItem} />
            ) : (
              <CloseIcon color={this.props.theme.toolbarItem} />
            )}
          </ToolbarButton>
        </LinkEditor>`

**Comment by tommoor** [comment]
Hey Adam, there is no way to change the placeholder text at this time – I'd recommend just forking the project and editing it!
