### ISSUE TITLE
Disable editing?

### ISSUE THREAD

**Issue by fangqiao** [outline/rich-markdown-editor#86]
Hi, i am trying your editor. So far it meets very well my need for a simple yet elegant editor.

I have a use case to use your editor as both display component and editing component. 
When as display component, in some cases I hope it is purely read only. Now I found that when the editor was set to readOnly, when the display area was double clicked, it was turned into editing mode. 

Is it possible to totally disable editing?

**Comment by tommoor** [comment]
Hi, there is no logic in this project to toggle readOnly on double click – can you reproduce this outside of your project?

**Comment by fangqiao** [comment]
Sorry I found out it is a bug of my code. The parent component handles double click which set the readOnly props to false. 
Please close this issue.
