### ISSUE TITLE
Is there a way to access underlying Slate state?

### ISSUE THREAD

**Issue by typpo** [outline/rich-markdown-editor#88]
I'm trying to integrate [slate-suggestions](https://github.com/oozou/slate-suggestions).  It requires the full Slate state (ie, a json schema containing a list of nodes).

This Editor's `onChange` prop passes a `getMarkdown` function.  Is there a way to access the underlying state of the Editor as well?

Thank you for this amazing project!  It's such a quality component that has saved me a ton of time.

**Comment by tommoor** [comment]
Howdy, noone has asked for that as of yet – you could create a custom plugin and pass it to the `plugins` array, you'd have access to everything then. Alternatively we could provide the state back as the second parameter in `onChange`

**Comment by tommoor** [comment]
FWIW, that plugin isn't really using the latest best practices – it shouldn't require you to separately render the portal and it could take care of that internally with the `renderEditor` hook. I'd imagine you're going to need to fork/refactor the plugin anyway so you might want to make that change instead

https://docs.slatejs.org/guides/rendering#the-editor-itself

**Comment by tommoor** [comment]
Closing as answered

**Comment by typpo** [comment]
Thank you, Tom.  I will see if I can write a custom plugin to take care of this :)
