### ISSUE TITLE
Docs: Please add "how to hide/disable buttons"

### ISSUE THREAD

**Issue by rkboyz124** [outline/rich-markdown-editor#92]
There was a PR for [hide/disabling toolbar buttons](https://github.com/outline/rich-markdown-editor/pull/35) a few months ago which was merged, but the docs wasn't updated on how to hide/disable button selection.

**Comment by chrkaatz** [comment]
Could it be, that this functionality has been disabled?

**Comment by ScottAgirs** [comment]
> Could it be, that this functionality has been disabled?

Did you ever find out the answer? : )

Is this possible with `rich-markdown-editor`? How can we modify the blocks/buttons?

**Comment by tommoor** [comment]
PR under way here: https://github.com/outline/rich-markdown-editor/pull/438
