### ISSUE TITLE
"Toolbar popup" & "Block Insert Button" z-index issue with Material-ui dialog/modal

### ISSUE THREAD

**Issue by rkboyz124** [outline/rich-markdown-editor#93]
### Bug or Enhancement
Bug

### What's The Issue/Purpose
"Toolbar popup" & "Block Insert Button" is overlapped when using material-ui dialogs/modals.

### Expected Output
They should not be overlapped by the dialog/modal.

### Reproducible Demo
[Check repo here to reproduce](https://codesandbox.io/s/richtexteditor-zindex-issue-reproduction-twxso)

### Other Notes
I've seen a merged [pull-request](https://github.com/outline/rich-markdown-editor/pull/82) to fix z-index issues but the issue still persists.
I hope this one would get fixed as soon as possible.

**Comment by olipo186** [comment]
Hi,

I encountered the same issue - also when trying to use the editor within a dialog/modal. The dialog simply has a higher z-index than the editor, causing the toolbar to appear behind the dialog.

The ability to configure a custom z-index would solve this issue. I submitted it as a PR: https://github.com/outline/rich-markdown-editor/pull/103
