### ISSUE TITLE
Asterisk (*) has to be escaped in code block, otherwise it vanishes on save

### ISSUE THREAD

**Issue by caljess599** [outline/rich-markdown-editor#97]
Typing the following into a code block:

`output=$(aws s3 sync . s3://welld-all-yaml-files --exclude ".git/*" --exclude ".gitignore") &&`

turned into this upon save:

`output=$(aws s3 sync . s3://welld-all-yaml-files --exclude ".git/" --exclude ".gitignore") &&`

I had to escape (with `\`) the asterisk to get it to save. Seems like a bug?

**Note: I noticed this behavior on getoutline.com, but I"m submitting it here because it seems to be an issue with the editor.**

**Comment by tommoor** [comment]
Howdy, unfortunately I haven't been able to reproduce this either on Outline or within this library – the "*" remains after save and reload in both code blocks and inline code.

**Comment by tommoor** [comment]
Ah, I've reproduced something – was there two "*" in the original?

**Comment by tommoor** [comment]
Fixed by https://github.com/tommoor/slate-md-serializer/commit/c6e2a2bbc647c37a44477736266a30dc78a5f989

This will be running in production shortly, thanks for the heads up

**Comment by caljess599** [comment]
Thank you. Just to complete the description, it only seems to be an issue on the first save. When the page is refreshed--the `\*` appears, not just the `*`. When I edit it again to remove the `\`, the `*` remains and it's all fine. Weird.
